### ISSUE TITLE
CreativeKillPotion

### ISSUE THREAD

**Issue by ravenje** [Wurst-Imperium/Wurst-Client#1027]
GarPloit 1.3 is now Avilable.
with a Potion, that can kill players in creative mode
https://www.youtube.com/watch?v=NsOGHuPn7Mg
19:57

**Comment by Alexander01998** [comment]
This link does not lead to a YouTube video.

**Comment by ravenje** [comment]
o sorry
https://www.youtube.com/watch?v=NsOGHuPn7Mg

**Comment by GummiBoat** [comment]
This should be fairly easy. "Instant Health potion.potency.125 (1:40)"

But seriously, is this guy doing nothing than searching exploits all day? ô.o

**Comment by OMGchangeMYusername** [comment]
> But seriously, is this guy doing nothing than searching exploits all day? ô.o

Tru

**Comment by Alexander01998** [comment]
> But seriously, is this guy doing nothing than searching exploits all day? ô.o

Most of them aren't really exploits, but items with NBT data.

**Comment by mcccs** [comment]
Let's deofuscate Garploit ;)

**Comment by GummiBoat** [comment]
There's already a Crack to get Premium on GarPloit 1.3.

[Download Link](https://mega.co.nz/#!c0JlGbxb!ET_PIR9YWoE0z2Zv1Fyhxt3JwHK8P7xXvMof_ZjwIbM) inclusive a german and an english tutorial.

Yes it takes some steps. But it works.

**Comment by Alexander01998** [comment]
> Let's deofuscate Garploit ;)

Been there, done that.

**Comment by ravenje** [comment]
@GummiBoat i using Linux and the crack for garploit only works on windows :/

**Comment by WurstContributer** [comment]
@GummiBoat How bout a potion that "bans" them from the server... FOREVER >:D

**Comment by scriptinator** [comment]
Lol I tried to deobsfucate garploit, but the source folders and classe's names were a bunch of weird letters

**Comment by GummiBoat** [comment]
@scriptinator "deobfuscation" is turning the "weird letters" to readable code. Because it's nothing than "obfuscated" (shuffled and renamed) text. What you tried is probably "decompiling" the jar to an overview of readable classes.

**Comment by scriptinator** [comment]
@GummiBoat I used Enigma, Hook-Manager, And JD-GUI each yielded the same thing

**Comment by GummiBoat** [comment]
@scriptinator If you really know what you're doing, you should know, that GarPloit definitely is not obfuscated with Enigma.

**Comment by scriptinator** [comment]
@GummiBoat I thought about that too and that is why I tried Hook-Manager and JD-GUI

**Comment by Alexander01998** [comment]
@scriptinator It's easy if you know what you're doing, but you can't just use a random piece of software and expect that it will do all of the work for you.

**Comment by scriptinator** [comment]
@Alexander1998 I believe that since Wurst is open source all of its folders are organized in a nice way (etc. Mods in the mods folder) or maybe that was just how it was made. I think a lot of other clients don't really care about this for example I looked at another client's code in Jd-Gui (Leakforums). It definitely was not as well-organized as Wurst's source code. I think you are misunderstanding my post about using Enigma,Hook-Manager, and JD-GUI. What I am saying is that to make sure I experimented with three different pieces of software I did not take the source code from Enigma and try and use it in Hook-Manager for example.

**Comment by Alexander01998** [comment]
@scriptinator The purpose of an obfuscator is to completely screw up the organized source code so that it is harder for people to read. The original source code of GarPloit looks completely different from the obfuscated source code.

Deobfuscating a Java program means re-organizing everything until you can understand it. Like I said, you can't just open it in a random decompiler or deobfuscation tool and expect that it will organize the code automatically.

**Comment by scriptinator** [comment]
Then how did you deobsufacate Garploit? Surely, you used a program. Or at least half-used a program to deobsfucate.

**Comment by ravenje** [comment]
is there a crack of Garploit 1.3 for Linux? (Debian)

**Comment by Whatisthisname** [comment]
PLease someone tell me if the link above for the GarPloit Crack is not a Virus, Chrome thinks it is.
I am worried, but i really want that feature wheere you can login with other players

**Comment by GummiBoat** [comment]
It's not a Virus. I'm using chrome too, I don't know what's wrong there...
