### ISSUE TITLE
GhostHand

### ISSUE THREAD

**Issue by mcccs** [Wurst-Imperium/Wurst-Client#1035]
![](http://i.imgur.com/rChWrPC.png)

**Comment by llaurenss** [comment]
should be a nice feature i think :)

**Comment by Alexander01998** [comment]
It's already possible through Freecam.

**Comment by Nitrogen-Dioxide** [comment]
Yea @Alexander01998 .... I think that garploit is making so much success because it only makes some tasks more.. accessible. Expect them to call blink a "super magic teleport hack" xD, because almost anyone knows how to use it right, every time I use it, owners/mods or any staff starts screaming wtf lel.

**Comment by Murplyx** [comment]
The GhostHand is really helpful and very usefull when you need to access something fast, it's also annoying to turn on freecam, fix fly speed.. bla, bla bla. Please add it Alex it'd be really awesome!
