### ISSUE TITLE
How does Flight trick NCP?

### ISSUE THREAD

**Issue by Murplyx** [Wurst-Imperium/Wurst-Client#1064]
I've seen the source of Wurst but I don't really understand how Flight with YesCheat+ tricks NCP with that 4 times loop that sends some glitchy position packets? Can someone please link to the part in NCP's source code where the glitch appears, or explain why this works?

**Comment by mcccs** [comment]
```java
@Override
	public void onEnable()
	{
		if(WurstClient.INSTANCE.modManager.getModByClass(YesCheatMod.class)
			.isEnabled())
		{
			double posX = Minecraft.getMinecraft().thePlayer.posX;
			double posY = Minecraft.getMinecraft().thePlayer.posY;
			double posZ = Minecraft.getMinecraft().thePlayer.posZ;
			for(int i = 0; i < 4; i++)
			{
				Minecraft.getMinecraft().thePlayer.sendQueue
					.addToSendQueue(new C03PacketPlayer.C04PacketPlayerPosition(
						posX, posY + 1.01, posZ, false));
				Minecraft.getMinecraft().thePlayer.sendQueue
					.addToSendQueue(new C03PacketPlayer.C04PacketPlayerPosition(
						posX, posY, posZ, false));
			}
			Minecraft.getMinecraft().thePlayer.jump();
		}
		WurstClient.INSTANCE.eventManager.add(UpdateListener.class, this);
	}
```

**Comment by GummiBoat** [comment]
@mcccs , he just stated, that he can't understand that part and you link it to him... :mag:

The Glitch appears, because the Code tries to teleport you up and down with a higher amount than you could jump normally.  (1.01) So NCP assumes that you're cheating and tries to bring you back to the ground. There's an option, that is called "falldamage", that will deal damage, if you tried to fly or jump too high, applying the same rules as vanilla fall damage, to "punish" the player. Then directly after you got damage, you jump and at that point NCP thinks you are falling, because you just got teleported back and received the damage. So as long as you're "falling" it won't check your movement anymore, as long as you're not too fast.

I hope that made it a little bit more understandable.

**Comment by Murplyx** [comment]
Do you think it will be patched in further versions of NoCheat+?

**Comment by GummiBoat** [comment]
This exploit existed a little while now, I don't think it'll get patched very soon.
