### ISSUE TITLE
FullBlink

### ISSUE THREAD

**Issue by mcccs** [Wurst-Imperium/Wurst-Client#1065]
Records all packets.

**Comment by Pkgts** [comment]
what does this mean

**Comment by pokeball99** [comment]
Um....I know what it means,bit I can't explain it well,I'm going to let one of the others explain it

**Comment by Bluscream** [comment]
My first guess is that Blink isn't recording all types of packets, so its just recording who are you attacking, where are you moving, what chests do you open and stuff ...
My second guess is that Blink is only recording 4000 packets max for example so its not beeing used infinte.

**Comment by GummiBoat** [comment]
Blink is already stopping all the Packets that are being sent by the client. So you still can see, what other people are doing etc. And FullBlink will also stop packets being sent to you from the server. It's like pausing the game, but you can still move.

**Comment by Meylama** [comment]
No @GummiBoat, that's wrong. The Blink description is Wurst says that it only records movement packets, and it is so, because if you place blocks during you blink, it does not send this to the server if you turn blink off. The "FullBlink" (of another Client) also records this, so you can also place and break blocks during you blink and if you turn blink off, it will send this to the server.

The second thing: FullBlink also records the chat, so if you write a chat message during blink, it will not send them immediately like in the current Wurst blink, it will send the message only when you disable blink.

**Comment by llaurenss** [comment]
I really want this.

**Comment by Eyremba** [comment]
@Alexander01998 this "FullBlink" has been suggested so many times, can you please implement it in the next update?
