### ISSUE TITLE
Chat messages whenever a mod gets enabled

### ISSUE THREAD

**Issue by OMGchangeMYusername** [Wurst-Imperium/Wurst-Client#1078]
idk what to call it,but it's swaggy,a lot of clients have it
Enabled:
`§c[§6Wurst§c] §aKillaura enabled`
Disable:
`§c[§6Wurst§c] §cKillaura disabled`
I think it's too easy to implement too,can someone make a pr for it please :wink: 
i don't know how to so yeah..

**Comment by Alexander01998** [comment]
I don't see any way how this could be useful, but I know from those other clients that it can quickly become annoying.

**Comment by OMGchangeMYusername** [comment]
Why not make it optional? it's just that it's swaggy and a lot of clients have it :heart:

**Comment by GummiBoat** [comment]
Just because other clients have it, it doesn't mean, that Wurst has to have it. I personally think this is completely useless. I don't need that much Information and I want my Chat to be clean. For example, if I would play some PvP gamemode and I don't want to be spoiled as a hacker, I regularly turn my Hacks on and off. And that would be very annoying over some time. I don't think that anyone wants that really... But that's only my personal Opinion.

**Comment by OMGchangeMYusername** [comment]
> Why not make it optional?

that'd basically solve it.
