### ISSUE TITLE
Packets [Glitch, Hack]

### ISSUE THREAD

**Issue by linuxcodefire** [Wurst-Imperium/Wurst-Client#1085]
When i was experimenting with the sign glitch with my friend i speed clicked it with fast place & break and it crashed both of use with minecraft error packet size to big [127] so if you are able to send any symbol in a sign like ##########################.... and bigger packets you could take down server right?

i would like to see a glitch build off this.

**Comment by linuxcodefire** [comment]
also possible sending forceop information by block encrypted packet clicks xD

**Comment by GummiBoat** [comment]
The Sign crash already got mentioned in #967. And how would "block encrypted packet clicks" send ForceOP Information? ForceOP doesn't work the way it did anymore. And next time, please read the [guidelines for contributing](https://github.com/Wurst-Imperium/Wurst-Client/blob/master/CONTRIBUTING.md), because you shouldn't place two enhancements in one Issue.
