### ISSUE TITLE
I Can't Join Lan Servers

### ISSUE THREAD

**Issue by billyoz** [Wurst-Imperium/Wurst-Client#1086]

**Comment by mcccs** [comment]
Did you try with vanilla client?

**Comment by billyoz** [comment]
What is Vanilla Client??? I'm Try With wurst

**Comment by OMGchangeMYusername** [comment]
Just in case if you don't know,LAN servers must be using the same network as you,idk that much about it,but i think both computers have to be in your house,or using the same internet (?)
(i misunderstood those for a long time so yeah)
But if you're saying you can join them with vanilla and not with Wurst,then it might be a bug or something.

**Comment by mcccs** [comment]
use hamachi

**Comment by OMGchangeMYusername** [comment]
It's laggier than my ass.

**Comment by WurstContributer** [comment]
LAN servers are servers hosted on your Local network so only people on that network can join.

**Comment by OMGchangeMYusername** [comment]
i dunno why i'm this bad at this,but it's basically what failvenom said.

**Comment by TekkitCommando** [comment]
@WurstContributer nice name bro xD

**Comment by OMGchangeMYusername** [comment]
@TekkitCommando Although it should be Contribut**o**r xD

**Comment by WurstContributer** [comment]
@OMGchangeMYusername Ok im changing it I never noticed that xD

**Comment by OMGchangeMYusername** [comment]
@WurstContributor You know for sure that Github doesn't save things before changing your name right? like failvenom is no more,and now,"WurstContributer" is no more!
you should be careful changing your name xD
and btw my name is like this because i tried several names and Github didn't change it,and then i got angry and wrote this and voila.. OMGchangeMYusername...
