### ISSUE TITLE
AuthMe - Can't Login to Multiplayer 

### ISSUE THREAD

**Issue by xXSpadesXx** [Wurst-Imperium/Wurst-Client#1103]
I dont know if this is just me... but after i get an admin from a server..
I 'use' their account right?
then i try tologin into that server using that account, but then it says
" Internal Exception : java.lang.NullPointerException "
So i cannot get the AuthMe to work, since i cant complete step one -.- 
Also I made sure the admins werent on the server or anything either. I dont know why thats not working...

----
Also a question:
If u have to 'Direct Login' to that admin or something, how am i supposed to know their password.. even when i tried to do that to my own account it said "Wrong Password" so im extremely confused -.-

(Is that enough information 0.0?)

**Comment by GummiBoat** [comment]
Well, I hope that you know, that you only can use cracked accounts on cracked servers. (Wurst should kick you, if that's not the case.) Otherwise I have no Idea why it's not working. Could you post a screen of the exact error?

Direct Login is only for premium Accounts, that you actually know the Username/EMail and password for. It works for me, if I use my own account.

"But it works on my machine!" so.. unless you post a little bit more Information with screens or videos, I can't really reproduce your errors.

**Comment by xXSpadesXx** [comment]
like more information like a screenshot of the error?

**Comment by GummiBoat** [comment]
For example, yes.

**Comment by Alexander01998** [comment]
# *Duplicate: #931*
![](https://camo.githubusercontent.com/fde0e4b68d36e2d72331263e4c421c56965a71df/687474703a2f2f692e696d6775722e636f6d2f714a4a514930582e706e67)
