### ISSUE TITLE
Wurst Launcher

### ISSUE THREAD

**Issue by Notchshero** [Wurst-Imperium/Wurst-Client#111]
Like nodus launcher,i dont want to drag all updates.

**Comment by Alexander01998** [comment]
A launcher and an auto-updater are two separate, independent things.

While an auto-updater might be nice, a Wurst launcher would be quite useless. The Minecraft launcher already has everything I need (even built-in Java :heart:) and no one is worried about typing their password into it because it's made by Mojang.

**Comment by Notchshero** [comment]
no, you didnt understand. you launch nodus launcher by minecraft launcher!

**Comment by Notchshero** [comment]
http://youtu.be/-NnXUzpEqOg?t=2m42s
watch from 2 42 to 3 52

**Comment by Alexander01998** [comment]
Still two separate things and still useless.
