### ISSUE TITLE
World Glitch?

### ISSUE THREAD

**Issue by KekkoMenny** [Wurst-Imperium/Wurst-Client#1127]
![2015-07-01_16 57 45](https://cloud.githubusercontent.com/assets/13101289/8450030/1ca2abb0-201a-11e5-9ce3-ab2938125e9d.png)

Sometime I got this problem that a part of the world keep "flash"/disappear and the only way to repair this is to restart Minecraft, this maybe a duplicate and Im sorry about that, but I didn't find a solution.

**Comment by GummiBoat** [comment]
Oh wow, that's really crazy, I never experienced this before. Do you know, if this only happens when you're using Wurst? Try keeping the launcher open and see if there occur any errors, while this bug happens. And some Information about your system would quite be helpful too. (Operating System, Java Version, especially your graphics card, etc.)

**Comment by Alexander01998** [comment]
That's almost certainly caused by your graphics card.

**Comment by OMGchangeMYusername** [comment]
Yep it was also happening coz of my shitty card or whatever it's called xD

**Comment by KekkoMenny** [comment]
Well what a sed story ahaha Thanks people.

**Comment by OMGchangeMYusername** [comment]
you might want to try pressing F3+A,i think it reloads the chunks or whatever,it works tho.

**Comment by KekkoMenny** [comment]
I'll try it, thanks :D.

**Comment by pokeball99** [comment]
This happens to me alot,it happens on most hack clients,I've can stop this by spamming xray and most of the time it works

**Comment by OMGchangeMYusername** [comment]
Xray pretty much does the same so yeah
