### ISSUE TITLE
Future?

### ISSUE THREAD

**Issue by linuxcodefire** [Wurst-Imperium/Wurst-Client#1136]
@Alexander01998 Can you look in to teaching us how to create a hacked client simular to yours? its open source but doesn't exactly show us how to put this and that here and their...

Good tutorial would be nice xD

**Comment by scriptinator** [comment]
I have made a tutorial on how to modify Wurst. As of this time I am waiting for the pull request to be merged onto the wiki. Until then there is a Debugging Wurst in Eclipse page on the wiki. Although it may be hard to understand :/

**Comment by mcccs** [comment]
He said that, he learned from this link: http://www.wizardhax.com/how-to-code-a-minecraft-hacked-client/

**Comment by linuxcodefire** [comment]
@mcccs that is outdated 1 version. Needs 1.8 tutorial.

**Comment by OMGchangeMYusername** [comment]
The way of coding didn't change that much (i doubt it even did),this is like the basics,learn them and you can figure out how to code one for 1.8 later.

**Comment by OMGchangeMYusername** [comment]
Btw duplicate #510 :smiling_imp:

**Comment by OMGchangeMYusername** [comment]
wanna know how did i find it? i simply used the word tutorial with this syntax `is:issue is:closed Tutorial in `
That's really simple,you could use other words but since i know that "Tutorial" isn't used that much,i could lure it out easily,please search for anything you want next time,it's so simple.
