### ISSUE TITLE
exploits for survival

### ISSUE THREAD

**Issue by dannyiscool4** [Wurst-Imperium/Wurst-Client#1141]
can you add some exploits for survival?

**Comment by GummiBoat** [comment]
The most "exploits" wurst has are NBT Data dependent, and in order to give  yourself items with NBT Data on it, you have to in creative mode.

Exploits like bypassing NCP can be achievend in survival, like Flight already does. I'm pretty sure, with time more exploits will get discovered, but currently there are none that work in survival.

**Comment by MicroChip321** [comment]
yes but how come wolfram has exploits in survival

**Comment by GummiBoat** [comment]
Well, that depends on the exploit itself, as said above. (Bypassing NCP, manipulating Packets (BookHack), etc.) If you say more specificly, what exploits "Wolfram" has, we can come up with a way to reproduce them.~
