### ISSUE TITLE
BackSprint

### ISSUE THREAD

**Issue by mcccs** [Wurst-Imperium/Wurst-Client#1203]
When you run to north while you are looking at south, sends to server:im looking at north

**Comment by OMGchangeMYusername** [comment]
this should be a seperate mod,some clients have the sprint mod always be able to sprint backwards which is easy to detect.

**Comment by Meylama** [comment]
This is called "AllDirectionSprint", and it does not sprint backwards, it can sprint in all directions. But it is very useful, so it would be nice to see it in Wurst

**Comment by mcccs** [comment]
I know, but th1s name is shorter.

**Comment by Nitrogen-Dioxide** [comment]
You don't need to say that you are facing anywhere, you only need to set the player speed to "sprint speed" all the time.

**Comment by Eyremba** [comment]
@Alexander01998 I saw in a commit that you added "SafeWalk" now. I would like to aks you to implement this "AllDirectionSprint" now, because SafeWalk in combination with this sprint method is awesome.

With SafeWalk, you can build a way from one sky island to another, if you enable it, walk backwards, and place blocks. But this process is a lot faster with this sprint, because you can also sprint backwards which allows you to place more blocks and build faster.

Here is a source of a sprint, which should be an "AllDirectionSprint": http://hastebin.com/naxeyepodi.axapta

**Comment by OMGchangeMYusername** [comment]
@Eyremba You want something swaggier? #781.
It's basically ScaffoldWalk but that's a different name.

**Comment by Eyremba** [comment]
@OMGchangeMYusername I know ScaffoldWalk :D it is pretty cool, but causes many NCP VL level, and that is the reason why it can not replase SafeWalk :D
