### ISSUE TITLE
Why isn't 2.1 released? [Question]

### ISSUE THREAD

**Issue by mcccs** [Wurst-Imperium/Wurst-Client#1229]

**Comment by TekkitCommando** [comment]
Cuz Alexander is too cool to release it yet xD

**Comment by mcccs** [comment]
XD

**Comment by TekkitCommando** [comment]
"TekkitCommando added the label question"

"TekkitCommando close this issue" xD

**Comment by TekkitCommando** [comment]
That's 
Great lol

**Comment by Alexander01998** [comment]
> Cuz Alexander is too cool to release it yet xD

Because of that and because I always release updates on Fridays.

The traffic is much higher on the weekends, so by releasing updates at the beginning of the weekend, they get downloaded a lot more often.
In Wurst v1.15, I made the mistake to release it on a Tuesday and it got a lot less downloads despite having a lot of exploits and other cool things in it.
