### ISSUE TITLE
Didnt disable killaura and went to a server. so annoying

### ISSUE THREAD

**Issue by Notchshero** [Wurst-Imperium/Wurst-Client#127]
I played hunger games with killaura.Then i disconnected. When i reconnect i couldnt move. Why? Because im in hub and killaura is enabled. I want a warning for this "Connecting  to a server with killaura. Do you want to disable it?"

**Comment by OMGchangeMYusername** [comment]
well it should simply stop killaura whenever you join a server 'cause a lot of servers have the game or lobby choose thing at your inventory.

**Comment by Alexander01998** [comment]
> I want a warning for this "Connecting to a server with killaura. Do you want to disable it?"

Since Wurst v1.6, it is possible to automatically do certain things when joining a server. This includes toggling mods, but not yet disabling them.

Here's how to do it:

1. **Start Spammer.**
2. **Open the `joinserver` script** by going to `File>Load spam from file` and selecting `autorun\joinserver.wspam`.
3. **Type the command(s)** that you want to execute. To toggle Killaura, type `.t killaura`.
4. **Save the script** by going to `File>Save spam to file` and selecting the file that you opened.
5. **That's it!** Whenever you join a server, Killaura will be toggled.

> well it should simply stop killaura whenever you join a server 'cause a lot of servers have the game or lobby choose thing at your inventory.

At least 99% of all servers do not have any plugins whatsoever. People who play on these servers often leave Killaura enabled on purpose.

**Comment by Notchshero** [comment]
but it toggles? I sometimes disable killaura.
