### ISSUE TITLE
Add more GUI Buttons

### ISSUE THREAD

**Issue by Bluscream** [Wurst-Imperium/Wurst-Client#1297]
I would suggest some more buttons for interacting with the server.

1. **Reconnect** Button in ESC menu.
2. Show **Delete Server** Button always when connecting failed not only for the first time.
3. Add **Empty Servers** Button to Server Cleanup. (Removes all Servers with 0 Players when enabled.)
4. Add **Not whitelisted** Button to Server Cleanup. (If thats possible)
5. Disable **Auto-Reconnect** if ".*banned.*" was found in the connection failed message.

Addition: Maybe if you are coming from a multiplayer server, automatically go to the multiplayer screen.

@Alexander01998 @Nitrogen-Dioxide @Huanjohn @UnidentifiedProfile @GummiBoat @TekkitCommando @ravenje @mcccs What do you guys think?

**Comment by OMGchangeMYusername** [comment]
1. buggy as hell in wolfram. (for me at least)
2. O.o
3. liked that,but it's not like servers with 0 players are always down or so - can be a bit inaccurate 
4. agreed
5. can be easily done manually.
6. can be easily done manually.

**Comment by GummiBoat** [comment]
1. Reconnect in the ESC menu would be neat. @OMGchangeMYusername that's probably your shitty internet, lmao.

2. That button should only show, if you try to connect to whitelisted servers. I don't think it should show everytime after a failed connection, because sometimes the server is only down for short maintenance, your internet is too slow, etc. etc. And you arleady can delete Servers, to which the Server List can't connect with the "Clean Up" Button.

3. I don't like that. I prefer empty servers, if i just want to grief them.

4. Not possible, sadly.

5. Yup.

6. Are you really that lazy... ?

7. Please.. don't do this again. You shouldn't put multiple suggestions into one issue, even if they are similar suggestions. Do you see, how hard it is to keep an overview? D:

**Comment by OMGchangeMYusername** [comment]
Nah dumbass, i used it once and then changed the server, but Ermagherd i was moving and bouncing everywhere and my chat went crazy. I realized that i was very weirdly playing on both servers,dunno why but that never happened again (since i never used it again) so i'm 99% it's because of it.

**Comment by mcccs** [comment]
1 Not needed
2 Yes
3 Yes
4 Yes but checking can take long time
5 Yes

**Comment by Bluscream** [comment]
WTF INVALID @Alexander01998 

YOU WANT A NEW ISSUE FOR EVERYTHING? OKAY YOU WANT IT, YOU GET IT!

**Comment by Bluscream** [comment]
@Alexander01998 u r complaining about the amount of issues and still want more? lOl, just LOL

**Comment by OMGchangeMYusername** [comment]
Shut up you douchebag, he's free to do whatever he wants..

**Comment by Nitrogen-Dioxide** [comment]
@Bluscream It is not what **he** wants, it is **how** github works.

@OMGchangeMYusername Don't be that agressive please...

**Comment by OMGchangeMYusername** [comment]
I was just a little pissed at how he talks.. Swearing just because his issue got closed..
But fine i'll chill.
