### ISSUE TITLE
Multiple Client Versions

### ISSUE THREAD

**Issue by reeved** [Wurst-Imperium/Wurst-Client#134]
Is it possible to have multiple versions of Wurst (and/or other clients) ready to use so that I can change between them easily using the profile changer in the Minecraft launcher?

Right now what I do is replace the folder in the Versions folder and delete the other Wurst folder containing the settings.

**Comment by Alexander01998** [comment]
Yes, you just need to rename them properly.

For instance, let's say you have downloaded the latest release and want to rename it from `Wurst` to `Wurst-MC-1.8`:

- **Rename the folder** `.minecraft\versions\Wurst` to `.minecraft\versions\Wurst-MC-1.8`.
- **Rename Wurst.jar** inside of that folder to `Wurst-MC-1.8.jar`.
- **Rename Wurst.json** to `Wurst-MC-1.8.json`.
- **Change this line** inside of `Wurst-MC-1.8.json`:
```JSON
"id": "Wurst"
```
to this:
```JSON
"id": "Wurst-MC-1.8"
```
- **That's it!** Restart your Minecraft launcher if you still have it open so that you can see the new version.
