### ISSUE TITLE
Spammer shuffle

### ISSUE THREAD

**Issue by Meylama** [Wurst-Imperium/Wurst-Client#1351]
Sorry my fault, look at this hastebin: http://hastebin.com/adisimadah.xml here it is shown correctly

**Comment by Meylama** [comment]
Sorry my fault, look at this hastebin: http://hastebin.com/adisimadah.xml here it is shown correctly

**Comment by OMGchangeMYusername** [comment]
There's a goddam edit button to the top right.....

**Comment by Meylama** [comment]
@OMGchangeMYusername I have GitHub since 1 week so sorry for that....

**Comment by OMGchangeMYusername** [comment]
Thought you're already used to it since you participated in several issues..
some useful steps:
- click on the http://puu.sh/j8PW0/7ab009ef4c.png in your first post.
- delete what you don't want, and then type whatever you want then save changes.
- click on the http://puu.sh/j8Q1l/0d936e7299.png in your second post.

x) too bored today

**Comment by Eyremba** [comment]
Could be a nice idea :) Well, I think the label "WSPAM" is missing here, or? @Alexander01998
