### ISSUE TITLE
Suggestions and Issue report.

### ISSUE THREAD

**Issue by pasi123567** [Wurst-Imperium/Wurst-Client#1362]
I love this client really much but it still has bugs and features that would be really cool to see :)

Bugs:
--- Alt manager doesnt save Accounts
--- Cant swim up when "NoSlowDown" is on
--- Cant move under water when "Jesus" is on
--- "Phase" gets through every block.. dont know where thats usefull
--- GUI is not sharp when playing on a big screen with auto GUI scaling
------- http://i.imgur.com/06ztnHX.jpg
--- When i turn off "Skin Blinker" every part of the skin should be turned on again

Suggestions:
--- If you press escape on a server or get kicked ther should be 2 buttons
------- "Reconnect"
------- "Reconnect with random alt account"
--- On the Server list in the "Clean Up" menu, a button to remove all "Grief me" Servers
--- The "Follow" Hack should have an command to follow a specific player
--- An way to remove signs on xray
--- An easier way to add hotkeys to hacks, like a list to choose a hack in the keybind manager
--- An Theme shop :) Where players can make themes for the client and publish them (or sell them)
--- Run while Inventory is open
--- And the last one :) Please add more things to "Fun", like all players are walking on 4 legs(if thats possible) and such things =)

I would be so happy if ALL of this will be added  =)

**Comment by Meylama** [comment]
"--- Alt manager doesnt save Accounts" 

Wrong. It saves the accounts

"--- "Phase" gets through every block.. dont know where thats usefull"

Biggest facepalm ever. Where thats useful?! Where could it be useful if you can get through blocks?! It can everytime be useful, also to get through locked doors and grief a base. Or if you are in a jail.

"--- GUI is not sharp when playing on a big screen with auto GUI scaling
------- http://i.imgur.com/06ztnHX.jpg"

That's your shitty grafic card / GPU, on my PC all is sharp.

"--- When i turn off "Skin Blinker" every part of the skin should be turned on again"

Was already suggested! Read the issue rules before opening an issue.

"--- An Theme shop :) Where players can make themes for the client and publish them (or sell them)"

Not possible because the theme is hardcoded.

And at least.... READ THE RULES BEFORE OPENING AN ISSUE! Onlye ONE issue per ticket is allowed, more than one issue in an issue ticket (like here) are forbidden and will NOT accepted.

**Comment by GummiBoat** [comment]
> Don't put multiple Issues into one issue. That makes them impossible organize and will likely get your issue ignored or removed.

Please consider reading the [guidelines for contributing](https://github.com/Wurst-Imperium/Wurst-Client/blob/master/CONTRIBUTING.md).

**Comment by TekkitCommando** [comment]
Actually themes are possible but you would have to code support for plugins in wurst to allow the changes, but something like that is a duplicate that's already been denied

**Comment by Bluscream** [comment]
> --- An Theme shop :) Where players can make themes for the client and publish them (or sell them)

Why the hell should i pay money for a simple theme on a free client?

**Comment by pasi123567** [comment]
Biggest facepalm ever. Where thats useful?! Where could it be useful if you can get through blocks?! It can everytime be useful, also to get through locked doors and grief a base. Or if you are in a jail.

Not... it goes through EVERY block even dirt or so that mean im falling constantly.

Its not my graphic card....

You dont need to sell them it was just a suggestion....

Alt manager doesnt save accounts for me so thats a issue

And sorry i will read it and then post all issues seperatly

**Comment by OMGchangeMYusername** [comment]
--- Cant swim up when "NoSlowDown" is on
That's what Noslowdown does.

--- Cant move under water when "Jesus" is on
what do you think Jesus is? it's about walking on the goddamn water.

**Comment by OMGchangeMYusername** [comment]
NO PLEASE DON'T

**Comment by pasi123567** [comment]
Yeah but i should still be able to swim up

**Comment by pasi123567** [comment]
I will add all issues seperatly with more information , also please dont blame me...
