### ISSUE TITLE
Packet Sneak

### ISSUE THREAD

**Issue by solidshadow96** [Wurst-Imperium/Wurst-Client#1404]
On a server i play on with no cheat my friend uses the JAM client. it has a feature PacketSneak it allows him to shift run without being caught by no cheat.

**Comment by OMGchangeMYusername** [comment]
um.. thought this is how it already works on Wurst? (i don't use Sneak) But yeah that'd be way better.

**Comment by Meylama** [comment]
@OMGchangeMYusername Wurst uses PacketSneak, but only if YesCheat+ is disabled. If you use YesCheat+, it is a simple "toggle sneak". But yes, there are many PacketSneaks which can bypass NCP, such as Flare, LateMod, etc. have.

**Comment by OMGchangeMYusername** [comment]
That's the problem, some mods are able to bypass but in Wurst they're just not, just as Blink was before #446.

**Comment by Meylama** [comment]
Yes @OMGchangeMYusername. There are also bypasses for NoSlowdown & Killaura etc. but in Wurst, it does not bypass. (Test the Wurst Killaura on a NCP Testserver with the newest NCP version, you get tons of flags and it will reset 9 out of 10 hits etc., this should also be fixed, because there are also other clients which get really less NCP flags.

**Comment by OMGchangeMYusername** [comment]
Agreed.
