### ISSUE TITLE
my name dosent fit in the op-sign exploit its GamingGamer21

### ISSUE THREAD

**Issue by EnderGamer21** [Wurst-Imperium/Wurst-Client#1409]
Fix it plz

**Comment by Meylama** [comment]
How does it not fit...? It should work with every name.

**Comment by MyzticalTekkno** [comment]
@MeyLama, i know what ender means, when u use op sign hack, a menu should popped up, and u can type any commands u want, but ender use it and use /op and then his username, but the problem is on typing his username, it wouldnt fit on the command box, or alex would add more space for it so player with long username can use it.

**Comment by Meylama** [comment]
@MyzticalTekkno the menu box should get longer and longer if the text is too long, so it should work.

**Comment by OMGchangeMYusername** [comment]
Well wouldn't that be a vanilla problem? even in Hypixel signs don't contain the full name, so yeah maybe you name is too long for a sign.

**Comment by Meylama** [comment]
You must NOT write your name on the OP-Sign, you must write your name ONLY into the menu that opens when you activate OP-Sign.

**Comment by OMGchangeMYusername** [comment]
Wait wot? I never tried it btw so i really don't know what's goin' on O.o

**Comment by OMGchangeMYusername** [comment]
@EnderGamer21 Just make sure you're in creative and in a server that hasn't patched it and it will work for sure. 
![image] (http://puu.sh/jiZNb/ffbe95474e.jpg)
