### ISSUE TITLE
crash exploit-effects

### ISSUE THREAD

**Issue by pokeball99** [Wurst-Imperium/Wurst-Client#1419]
u can crash anyone's client and make them not able to log back in by do this,they must be in survial to get them to crash,it works by giving them a float number of health.
https://www.youtube.com/watch?v=SxH5JlTezIM (dont know the timestamp)
maybe with op we could have some kinda command that:
1.puts this effect on all players
2.puts all players in gamemode 0(except for yourself of course)
/entitydata  @e[type=MOBNAME] {AbsorbtionAmount:-3.500000000000000000000000000.0f}}

**Comment by OMGchangeMYusername** [comment]
hm.. i got what you say, but just where can it be useful? i mean what kind of server makes you in gm1 and others in gm0? sorry if i forgot something important.

**Comment by pokeball99** [comment]
@OMGchangeMYusername i mean that any players that are not in survival would force them into survival to crash them

**Comment by pokeball99** [comment]
or with cracked server u could likely just log in with there name and do it to yourself

**Comment by OMGchangeMYusername** [comment]
> i mean that any players that are not in survival would force them into survival to crash them

Since when forcing players into survival is possible? exploit?
> or with cracked server u could likely just log in with there name and do it to yourself

That may be useful, but still you'll have to know his password first..

**Comment by pokeball99** [comment]
>That may be useful, but still you'll have to know his password first.
mainly cracked servers that dont have password,or u are ocd enough to bruteforce all of them with forceop
>Since when forcing players into survival is possible? exploit?
 >maybe with op we could have some kinda command that:

**Comment by GummiBoat** [comment]
There is no information whatsoever, on how to recreate that to actual use on players. Atleast I didn't found anything.

**Comment by OMGchangeMYusername** [comment]
Oh so the whole thing is *after* you get OP.. well these are some conditions..

**Comment by pokeball99** [comment]
well idk if u could do this in gamemode 1,but i assume that u can give effects to players with only gm1...

**Comment by MyzticalTekkno** [comment]
@pokeball99, you can't use /effects on gamemode 1 bro, because thats an operator command, and
i neverseen a cracked server without an auth plugin, force op? force op ain't real bro face it, getting op isn't easy as you think even if you use hacks like book hack, book hack requires book & quill & an operator (many operators seen book hack in action on many server), And Sign OP Requires Vanilla Server which is 1.8.3- , and Force people to be on survival? how?, Bruteforce? (in mind: wow bro you must've watched tons of fake force ops and brute force hacks :P)

TIP: you can just use CrashSign on other hacked client like wolfram, or alex will added the exploit to the client? who knows? (in mind: god knows xD)

**Comment by pokeball99** [comment]
well im sorry to say this @MyzticalTekkno but your newness is showing,what im am talking about is:
>i neverseen a cracked server without an auth plugin, force op? force op ain't real bro face it

> Force people to be on survival? how?, Bruteforce? (in mind: wow bro you must've watched tons of fake force ops and brute force hacks :stuck_out_tongue_closed_eyes: )

1:the force op im talking about is wurst's,which is a cracked server auth plugin bruteforcer

> wow bro you must've watched tons of fake force ops and brute force hacks :stuck_out_tongue_closed_eyes: 

2.this assume im some 7 year old tryhard who wants to impress his freinds,which im not,you are too quick to judge,and since u have only been here for ~12 days and i have been here for ~4-5 months,that would say that i know a little more about what im talking about than u

>and Force people to be on survival? how?

3.with op,or some other method that similar to the bookhack

>you can't use /effects on gamemode 1 bro,

4.
>but i assume that u can't give effects to players with only gm1...
and i think that is all i have to say for you,have a nice day good sir

**Comment by GummiBoat** [comment]
I see that I need to repeat myself. The problem is, you can't give yourself, a player, entitydata or to be more specific, the AbsorptionAmount mentioned in the video just by command or potions. Additionally, if the number is too much for java to handle, how is Alex supposed to implement it? Eclipse will instantly throw out an error and if you try it out on an actual client, it'll probably just crash yourself. Understood the problematic? This has nothing to do with getting into creative mode. (which is - honestly spoken - fairly easy, if you're atleast a bit skilled at social engineering.)

**Comment by pokeball99** [comment]
well idk,im not a coder here,just a braindump,u guys (aka @Alexander01998 @Nitrogen-Dioxide @bluscream) are the ones that would figure that out,if @Alexander01998 saids it not possible then its not,but till then,we assume it is,and figure out how to get it to work

**Comment by 1337HaxorKiddie** [comment]
I think its possible to Generate Spawneggs which have this 3.500000000000000000000000000.0f  Amount here. If this is working that would be very cool because then we can Troll people with Godmode-Zombies or something like that xD

**Comment by Nitrogen-Dioxide** [comment]
... The /summon command can spawn entities that doesn't don't death.

**Comment by OMGchangeMYusername** [comment]
> can spawn entities that doesn't don't death.

"can spawn entities that don't die"?

**Comment by Nitrogen-Dioxide** [comment]
@OMGchangeMYusername 

Yes there is no reason to put infinite health if you can do "creative mode" entities.

**Comment by GummiBoat** [comment]
^ exactly. There is a tag, called "Invulnerable". If you set that to 1, the entity won't die, unless you kill it with the /kill command, or kill it while you're in creative mode.

Well, this AbsorptionAmount even makes it Invulnerable for /kill and creative attacks, but you still can kill it with /entitydata or teleporting it into the void.

Additionally, even if we COULD apply that to a spawnegg, there aren't many servers, that actually allow  spawneggs being used.

Dunno. I just don't like this Idea overall.

**Comment by 1337HaxorKiddie** [comment]
OK, THX for the Information.

**Comment by Bluscream** [comment]
I would merge this with the creative .give command. I think it would be cool to have a NBT folder where you can add .json nbt files that you can just use with .summon <id> <file> and .give <id> <file> so we can keybind them. That would stop the issues about this since then we had a new "gallery" on the wurst website with usermade NBT data templates.

**Comment by 1337HaxorKiddie** [comment]
Jep that would be cool. @Bluscream

**Comment by PixelMaster3D** [comment]
It could be possible to spawn eggs. On version 1.5.2, the server I was on had unbanned Minecarts.

**Comment by Al00X** [comment]
I do this with : " All u want " mod !
HIGH health effect + VERY hi Speed makes the player crash and never comeback !
very fun :D ! but all u want I not for 1.8 :( very bad 
can create this crash effect with .potion

**Comment by PixelMaster3D** [comment]
That could crash the client, yes, but if a person had i high processor for PC/Server, that would be almost impossible for the server.

**Comment by Al00X** [comment]
if not potion , add attributes to item ... I tested and crashed some people in 4 different servers ...

**Comment by PixelMaster3D** [comment]
mentioning client as well if they have an improved CPU.
