### ISSUE TITLE
Increased item range?

### ISSUE THREAD

**Issue by superluig164** [Wurst-Imperium/Wurst-Client#1695]
Add a hack that causes your item pickup radius to be larger?

**Comment by OMGchangeMYusername** [comment]
Duplicate #144 
Search old issues next time ;)

**Comment by superluig164** [comment]
I did, and nothing came up...

**Comment by OMGchangeMYusername** [comment]
Don't search "Increased item range?".. 
Search for words that are related to your suggestion, read [this article] (https://help.github.com/articles/searching-issues/) about how to easily search what you want.
You'll most likely find issue number 849, because of the words there, but then you'll see that it's a duplicate of 144 and that way avoid duplicating ;)
