### ISSUE TITLE
YesCheat+ mode for NoSlowdown

### ISSUE THREAD

**Issue by Nitrogen-Dioxide** [Wurst-Imperium/Wurst-Client#175]
No slow down is great, but one thing is that it "noslow" water and "right click sword" too. so NCP keeps laging you.
A fix for that is while YesCheat+ is enabled. noslowdown stops "noslowing" water and sword protects, but keeps "noslowing" food/bow/etc

**Comment by Alexander01998** [comment]
> stops "noslowing" water and sword protects, but keeps "noslowing" food/bow/etc

Technically, there is no difference between the slowdown from swords, bows and food. It is all just called slowdown from items.

And because Minecraft makes no difference there, I highly doubt that NoCheat+ does. Not only would that need to be done manually (i.e. `if(slowdownBlocked && item instanceof ItemSword)`), but it would also be slower and less secure than just checking all items (i.e. `if(slowdownBlocked)`).

It's hard to test this now that NoCheat+ servers are going extinct (the big ones are all using *homemade* protections), but from my experience, other clients usually disable NoSlowdown entirely when switching to bypass mode.

**Comment by Nitrogen-Dioxide** [comment]
probably the "slowdown" is different in the server side :p .
