### ISSUE TITLE
Xray Glitch

### ISSUE THREAD

**Issue by AmazingGamer** [Wurst-Imperium/Wurst-Client#1837]
It always glitches when I use xray and it dosent render plz help

**Comment by OMGchangeMYusername** [comment]
Please read the [guidlines for contributing] (https://github.com/Wurst-Imperium/Wurst-Client/blob/master/CONTRIBUTING.md) to this repository.
You have to include a screenshot if it's about something visible, we can't really understand what happened just by "xray glitch it doesnt render"..

A possible reason is that you don't have any block on your xray list, since `.xray list` isn't working, press Esc--> Wurst Options--> X-Ray Blocks and see if there are blocks.

**Comment by Alexander01998** [comment]
If you are trying to say what I think you're trying to say, then you just haven't updated to Wurst 2.2 yet.
