### ISSUE TITLE
AutoTool "Ghost Blocks"

### ISSUE THREAD

**Issue by awakened-game** [Wurst-Imperium/Wurst-Client#1862]
AutoTool causes what I call "Ghost Blocks", I've noticed it for a while but i decided to report it today.

It happens in both singleplayer and multiplayer on both local and remote servers.
Tested:  Vanilla, Bukkit, Spigot, all 3 have the same effect

How to reproduce the "Ghost Blocks":
1. Turn on AutoTool
2. Select your sword in your hotbar
3. Have a shovel in your hotbar too
4. Break some grass, dirt, or any other block that makes AutoTool switch to the spade
5. Walk on the spot where you broke the "spadeable" block
6. Spaz out
7. Fly up away from the Ghost Block to exit your mini-freakout
8. Place any(?) block where the Ghost Block is and it will turn back into what was originally there
9. Mine it again and the Ghost Block should be gone
~~10. Post an issue on github to see if its just you, lol~~

Sorry for all the text, but my internet cant upload anything bigger than 800KB or so, so i couldnt post a video, and images wont help in this case.

In case its my sword or spade (unlikely, it happens a lot regardless), here are the enchantments on them:

Sword=ench:[{id:16,lvl:10},{id:17,lvl:10},{id:18,lvl:10},{id:19,lvl:10},{id:20,lvl:10},{id:21,lvl:10}]
Spade=ench:[{id:32,lvl:10},{id:33,lvl:1},{id:35,lvl:10}]

Oh and I'm pretty sure I coined the term "Ghost Block", if not, let me know.

>Ghost Block
>/ɡəʊst blɒk/
>
>_noun_
>
>1. A block in minecraft that when mined displays as minecraft:air to the client but the server sees the block as unmined and the player cannot pass through it.
>
>2. A ghost-like block, probably transparent.

**Comment by GummiBoat** [comment]
Beautiful Issue. Yup that's correct. If you break blocks too fast, the server rejects it, but your client shows them as broken. A ghost block. But it has to do with the enchants. Any efficiency above 3 will break the block too fast while switching tools. (Atleast with spades.) I don't think this can be fixed tho, because the switching itself is the problem. After your first broken block (the ghost block) every other block you destroy while continuing to hold your mouse button will break normally.

But note, that this only happens with the shovel, because shovels break their corresponding blocks faster than a pickaxe/axe.
![shovel](https://cloud.githubusercontent.com/assets/10976441/9292873/d8e109a2-440f-11e5-8384-2e14b958f496.gif)

**Comment by mcccs** [comment]
Adding a 10 ms delay may fix it.

**Comment by GummiBoat** [comment]
> I don't think this can be fixed tho, because the switching itself is the problem

This has nothing to do with delay. The problem is, that you're beginning to hit the block with another tool and then you're destroying it instantly after that. The server doesn't like such thing
