### ISSUE TITLE
block hack

### ISSUE THREAD

**Issue by linuxcodefire** [Wurst-Imperium/Wurst-Client#1948]
Similar to book hack... but with a block simply you create a block with a command off exploit menu... and ask an op to place it. After he places it you get op.. or selected command.

**Comment by 1337HaxorKiddie** [comment]
Impossible.

**Comment by OMGchangeMYusername** [comment]
Even if this would work, its requirements are hard&suspicious af.

**Comment by linuxcodefire** [comment]
Possible.. but you haven't tried :/

**Comment by 1337HaxorKiddie** [comment]
@linuxcodefire Its impossible in the 1.8 and 1.7 because the Force OP Hack (doestn´t matter if CMD Block, CMD Block Minecart or a Sign) works with the Command NBT Tag shown here: http://minecraft.gamepedia.com/Tutorials/Command_NBT_Tags#Blocks_2    and this NBT Tag doesn´t exist for normal Blocks. This NBT Tag works only for the 3 Force OP Blocks.

**Comment by linuxcodefire** [comment]
...

**Comment by 1337HaxorKiddie** [comment]
@linuxcodefire I think you have no idea whats possible and whats not. All your issues are impossible to do. Coding is not like: hmm i hack Mojang, thats a good idea... 
5 mins. later: 
Done.

Btw The Server would block this mod. Because its SERVERSIDED. To change this you must hack the Server to do this! And if you can hack the Server, its no problem for to get OP without any InGame Bloks or stuff.

**Comment by linuxcodefire** [comment]
You don't have to flip about it..

**Comment by 1337HaxorKiddie** [comment]
@linuxcodefire i don´t do, i only tell you why this is not working.

**Comment by linuxcodefire** [comment]
Sorry I look up to one of my friends who could do this :/

**Comment by MyzticalTekkno** [comment]
@1337HaxorKiddie True, you can't just easily hack the server, even if you didn't break the database cloud protection system (based on their hosting provider(mcprohosting = anti ddos.etc)). and normal blocks cannot contain NBT Tag for force op, because it's not executable entity like sign, book, command block.

**Comment by pokeball99** [comment]
@Alexander01998 we need to tag these,there are over 4 pages of unlabeled issues
