### ISSUE TITLE
Inventory move and more

### ISSUE THREAD

**Issue by auererik** [Wurst-Imperium/Wurst-Client#1997]
Hello

can you add a feature that you can run in your inventory

or you can take your items in your crafting slot without dropping

Like Wolfram(the hack is More Inv and Inven move)

**Comment by Eyremba** [comment]
Duplicate issue and INVALID because you must not suggest more than 1 thing in 1 issue.

**Comment by WurstContributor** [comment]
@Eyremba not invalid hes just giving two examples

**Comment by OMGchangeMYusername** [comment]
@WurstContributor It is invalid. He suggested two completely different mods in one issue, although there are some clients that merge this together and leave both as options.

And just in case you couldn't find it, they are both suggested and both are "pending decision", which is sad since both are amazing.
