### ISSUE TITLE
Let Mods Work With Wurst!!!

### ISSUE THREAD

**Issue by MrCreeper119** [Wurst-Imperium/Wurst-Client#2009]
Ive done it multiple ways and i STILL cant mod Wurst! Help!
plz let me mod wurst i want to be able to add TooManyItems!

**Comment by awakened-game** [comment]
if you know java at a medium level, you can put liteloader in wurst and use liteloader mods.
but you have to reeeally tweak how it works, because if you just install it normally, it will just load vanilla minecraft with liteloader, not wurst with liteloader, its a pain, but possible, maybe there's a guide somewhere?

**Comment by WurstContributor** [comment]
Duplicate

**Comment by OMGchangeMYusername** [comment]
Yea this is duplicate #777. Please look for old issues next time.
