### ISSUE TITLE
Close the issues section again

### ISSUE THREAD

**Issue by OMGchangeMYusername** [Wurst-Imperium/Wurst-Client#2034]
It's getting spammy and I can see you can't handle everything, close it and use the news in https://www.wurst-client.tk/news/ to tell people you need time to concentrate, you didn't close it that much time so no one will complain.

**Comment by Alexander01998** [comment]
I am currently working on a new system that will replace the Issues once it's finished.
However, disabling the Issues would not only stop people from opening new issues but would also stop them from reading existing ones.
Because of that, I will probably leave the Issues enabled even after the new system rolls out.
