### ISSUE TITLE
CrashHead Exploit

### ISSUE THREAD

**Issue by artbarte** [Wurst-Imperium/Wurst-Client#2054]
The exploit who kick people from server like on this video: www.youtube.com/watch?v=LxAKwzNy-78

**Comment by TheBoyIsHere** [comment]
like thet!
how heppy i ill be if it will heppen!

**Comment by linuxcodefire** [comment]
Wow

**Comment by solidshadow96** [comment]
THAT IS AWSOME ADD IT IN WURST 2.3.3 PLZ

**Comment by Garkolym2** [comment]
Yea! Alexander01998 is back! And he copy&pasting again :) Bravo alexander!

**Comment by Garkolym2** [comment]
Ill upload the second hatevideo soon

**Comment by Garkolym2** [comment]
mcccs, dass du dich sofort an die arbeit setzt und anfängst sowas zu skidden, ist schon arm oder? Du wirst nie eigenes machen können, weil du planlos und unkreativ bist.

**Comment by PixelMaster3D** [comment]
Seems like :mention:Garkoylm2 is telling the guy of that video something.

**Comment by PixelMaster3D** [comment]
Garkolym 1 hour ago (edited)
 The Coder of wurst, trys to copy&paste it. Please hate him.
https://github.com/Wurst-Imperium/Wurst-Client/issues/2054
He copy from me too, do some shit on his github page or add him on skype.
He will make it opensource and it will be fixxed.

**Comment by PixelMaster3D** [comment]
Thats a little abusive.

**Comment by solidshadow96** [comment]
Thanks for adding it :)

**Comment by PixelMaster3D** [comment]
You're Welcome! :laughing:

**Comment by Orcunegeacar** [comment]
Guys, Garkolym is warning the creator of this exploit on the video's comments. Pixel master 3d already said it too
![image](https://cloud.githubusercontent.com/assets/11218527/9585962/a1c6ec7e-5022-11e5-841b-3f279a58deec.png)

**Comment by PixelMaster3D** [comment]
Thanks for noticing!

**Comment by tal1z** [comment]
Hey guys. I'm not the creator of the exploit but I am the person who used it in the video. I would really appreciate it if you guys could not add this onto your client, because it will get patched and nobody will be able to use it. Please consider giving up on trying to find how it works if you haven't already, as it will ruin it for everybody. I know that big hacked clients like you only care for money and such, but ya know, it's a fun little thing I do every once and a while and I don't want it to get ruined. Thanks.

**Comment by tal1z** [comment]
Thanks for ruining it for everybody.

**Comment by solidshadow96** [comment]
Anyone know when Wurst 2.4 is comming out plz tell me

**Comment by pokeball99** [comment]
@solidshadow96 releases always are on friday

**Comment by solidshadow96** [comment]
YES thx

**Comment by solidshadow96** [comment]
i never knew
is it gonna be wurst 2.3.3 or is it gonna be the full wurst 2.4?

**Comment by Orcunegeacar** [comment]
Probably 2.4 because crash head exploit is a big update.

**Comment by solidshadow96** [comment]
Yea HUGE

**Comment by Nitrogen-Dioxide** [comment]
I think I just discovered how the crash head works, and I'll post it here because I just don't care about those stupid kids screaming out on YouTube instead of help this client and because I researched by myself.

First I read the Minecraft wiki and I found an interesting thing about head NBT tags:

![2015-09-02_23-12-37](https://cloud.githubusercontent.com/assets/11248300/9649341/fdac6b24-51c9-11e5-8b62-f9a58cccb58a.png)

Next, I just found an head generator that generates that ids.

![2015-09-02_23-14-42](https://cloud.githubusercontent.com/assets/11248300/9649345/128d70b0-51ca-11e5-9838-bab44268a732.png)

Well it worked with the internal wurst .give command, so I thinked, if I made an invalid id?

![2015-09-02_23-17-58](https://cloud.githubusercontent.com/assets/11248300/9649371/592eecce-51ca-11e5-863f-0e1127cefd8d.png)

And that was the effect:

![2015-09-02_23-29-02](https://cloud.githubusercontent.com/assets/11248300/9649408/da22d94e-51ca-11e5-9ab4-ddde9a5d620a.png)

On multiplayer:

![2015-09-02_23-17-20](https://cloud.githubusercontent.com/assets/11248300/9649423/2127e960-51cb-11e5-8762-896ac416db4e.png)


So, I think that to make this exploit, we need protect wurst from "inventory crash" and "chunk crash", and when the bugged ID head is on the chunk, everyone that loads it will got disconnected with the same message. You can see on the video that this is exactly what happens.

Note that this can make a new type of crash chest.

**Comment by solidshadow96** [comment]
cool i think i understand. i think...

**Comment by kim-yannick** [comment]
Thats interesting. Does it also work in the latest Spigot/Vanilla 1.8.8?

**Comment by mcccs** [comment]
Wow

**Comment by mcccs** [comment]
@Nitrogen-Dioxide it only crashes given player (@p)
but, if i change to @a everyone crashes, but i need be OP.
i think #2059 is the real crashhead

**Comment by Eyremba** [comment]
@Nitrogen-Dioxide first, I found this "singleplayer" crasher a few days before you and NO, it does not work correctly in multiplayer. Because Wurst crashes after the creation of this head, I set the head on a multiplayer with /setblock and this head had the same NBT data like the head which was created by wurst, but it has not lead to a crash of me or my friends, also if they stand next to the head. I also talked with the owner of the YouTube Video, and he says too that it is another way he is using.
And second: I had a conversation with asofold, the developer of NCP and he said the he is looking and this repository here, so you can be shure, as soon as Wurst has the Head exploit, it will be fixed by NCP. It was the same with the damage bypass. You can go on the NCP testserver where the newest NCP version runs, turn on "YesCheat+" and enable "Fly", you won't get damage and you won't be able to fly.

**Comment by Eyremba** [comment]
@Nitrogen-Dioxide first, I found this "singleplayer" crasher a few days before you and NO, it does not work correctly in multiplayer. Because Wurst crashes after the creation of this head, I set the head on a multiplayer server with /setblock and this head had the same NBT data like the head which was created by wurst, but it has not lead to a crash of me or my friends, also if they stand next to the head. I also talked with the owner of the YouTube Video, and he says too that it is another way he is using.

**Comment by Nitrogen-Dioxide** [comment]
@Eyremba Err.. but why don't share.

    Id: UUID of owner. Optional. Used to update the other tags when the chunk 
    loads or the holder logs in, in case the owner's name has changed.

I think that you need to load or reload the chunk to it works.
F3 + H reloads it.

**Comment by Eyremba** [comment]
1. Did the guy in the video reload it? No.
2. Like I said, my friends stand next to the head and they don't crasht.
and 3. Why don't share? I have not shared it because asofold from NCP is watching this repository here and he fixed also the fly-damage exploit because of this.

**Comment by Nitrogen-Dioxide** [comment]
@Eyremba 
    I think that you need to **load** or reload the chunk to it works.

Please, read!

**Comment by Eyremba** [comment]
@Nitrogen-Dioxide like I said, we tried different things and it didn't work, and in the video, the guys which crashed also didn't reload anything. And at least: did you read what I writed above?  "I also talked with the owner of the YouTube Video, and he says too that it is another way he is using."

**Comment by Nitrogen-Dioxide** [comment]
@Eyremba 

Well... there are new ways to do that ( coding rule ) so this doesn't affect anything. Like killaura, there are a ton of clients, and each client is different. I'll stop talking to you because this is not the best place for that.

**Comment by tal1z** [comment]
@Eyremba

I dont remember talking to you 0.o

**Comment by BladeWillBe** [comment]
You guys have serious problems. Can't we just leave one exploit unfound, so Mojang can't ruin our fun?

I happen to be a friend of the guys in the video and use the exploit myself. I cannot reveal how it is done, but I ask that you please just leave it be.

**Comment by Huanjohn** [comment]
@BladeWillBe But then we wouldn't be able to use it.

**Comment by Eyremba** [comment]
@tal1z I have a different name on each site. On leakforums, on github, on skype, on youtube... I asked under another name.

@BladeWillBe yes if the exploit would be in Wurst, NCP and maybe also Mojang would fix it.

**Comment by PixelMaster3D** [comment]
They will patch it but i'm asking Alex to list some of the sources private, so it will be harder to find out what the bug is.

**Comment by Al00X** [comment]
this crasher will crash forever ??? :O

**Comment by PixelMaster3D** [comment]
Mojang:copyright: will find the exploit anyway whether anyone likes it or not

**Comment by Al00X** [comment]
I don't get what is the head do :| , we put it will crash or we put it on out head ???
I saw video but don't get

**Comment by PixelMaster3D** [comment]
When you get a head from the client mod, it has been coded to crash the server/kick people from the server. When you place them down they start to add data to the server, and the more the data the more the server can try to keep up with.

**Comment by Al00X** [comment]
ooo thx

**Comment by Al00X** [comment]
lol 
.give skull 1 3 {display:{Name:"CRASHES MINECRAFT, BE CAREFULL"},SkullOwner:{Id:"CRASH ID"}}

this code crashed Wurst ! :D

**Comment by solidshadow96** [comment]
Is the update out yet ? Or can someone tell me when it is

**Comment by PixelMaster3D** [comment]
check the milestone

**Comment by PixelMaster3D** [comment]
It has percentage on how far the update is completed.

**Comment by solidshadow96** [comment]
where is it

**Comment by BoomBoomLHack** [comment]
```---------------- Wurst Client Crash Report ----------------
---- Please report this crash at: wurst-client.tk/bugs ----
// I blame Apple.

Time: 9/5/15 10:25 AM
Description: Rendering item

java.lang.IllegalArgumentException: Name and ID cannot both be blank
	at com.mojang.authlib.GameProfile.<init>(GameProfile.java:25)
	at net.minecraft.nbt.NBTUtil.readGameProfileFromNBT(NBTUtil.java:48)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererChestHelper.renderByItem(TileEntityRendererChestHelper.java:45)
	at net.minecraft.client.renderer.entity.RenderItem.func_180454_a(RenderItem.java:160)
	at net.minecraft.client.renderer.entity.RenderItem.func_180450_b(RenderItem.java:382)
	at net.minecraft.client.renderer.entity.RenderItem.renderItemAndEffectIntoGUI(RenderItem.java:422)
	at net.minecraft.client.gui.GuiIngame.func_175184_a(GuiIngame.java:1139)
	at net.minecraft.client.gui.GuiIngame.func_180479_a(GuiIngame.java:456)
	at net.minecraft.client.gui.GuiIngame.func_175180_a(GuiIngame.java:177)
	at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1158)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1298)
	at net.minecraft.client.Minecraft.run(Minecraft.java:383)
	at net.minecraft.client.main.Main.main(Main.java:127)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.mojang.authlib.GameProfile.<init>(GameProfile.java:25)
	at net.minecraft.nbt.NBTUtil.readGameProfileFromNBT(NBTUtil.java:48)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererChestHelper.renderByItem(TileEntityRendererChestHelper.java:45)
	at net.minecraft.client.renderer.entity.RenderItem.func_180454_a(RenderItem.java:160)
	at net.minecraft.client.renderer.entity.RenderItem.func_180450_b(RenderItem.java:382)

-- Item being rendered --
Details:
	Item Type: net.minecraft.item.ItemSkull@18b40fe6
	Item Aux: 3
	Item NBT: {SkullOwner:{Id:"CRASH ID",},display:{Name:"CRASHES MINECRAFT, BE CAREFULL",},}
	Item Foil: false
Stacktrace:
	at net.minecraft.client.renderer.entity.RenderItem.renderItemAndEffectIntoGUI(RenderItem.java:422)
	at net.minecraft.client.gui.GuiIngame.func_175184_a(GuiIngame.java:1139)
	at net.minecraft.client.gui.GuiIngame.func_180479_a(GuiIngame.java:456)
	at net.minecraft.client.gui.GuiIngame.func_175180_a(GuiIngame.java:177)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['BoomBoomLHack'/1145580, l='MpServer', x=-379.50, y=4.00, z=-1756.50]]
	Chunk stats: MultiplayerChunkCache: 361, 361
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: -375.00,4.00,-1760.00 - World: (-375,4,-1760), Chunk: (at 9,0,0 in -24,-110; contains blocks -384,0,-1760 to -369,255,-1745), Region: (-1,-4; contains chunks -32,-128 to -1,-97, blocks -512,0,-2048 to -1,255,-1537)
	Level time: 76 game time, 76 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 5 total; [EntitySlime['Slime'/1158151, l='MpServer', x=-385.48, y=4.55, z=-1691.92], EntitySlime['Slime'/1159832, l='MpServer', x=-338.50, y=4.00, z=-1814.84], EntityPlayerSP['BoomBoomLHack'/1145580, l='MpServer', x=-379.50, y=4.00, z=-1756.50], EntitySlime['Slime'/1159212, l='MpServer', x=-348.00, y=4.00, z=-1811.25], EntitySlime['Slime'/1164252, l='MpServer', x=-334.50, y=4.70, z=-1763.53]]
	Retry entities: 0 total; []
	Server brand: vanilla
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.addWorldInfoToCrashReport(WorldClient.java:393)
	at net.minecraft.client.Minecraft.addGraphicsAndWorldToCrashReport(Minecraft.java:2925)
	at net.minecraft.client.Minecraft.run(Minecraft.java:405)
	at net.minecraft.client.main.Main.main(Main.java:127)

-- System Details --
Details:
	Minecraft Version: 1.8
	Wurst Client Version: 2.3.2 (latest: 2.3.2)
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_45, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 214454728 bytes (204 MB) / 434470912 bytes (414 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: Wurst
	LWJGL: 2.9.1
	OpenGL: ATI Radeon HD 4200  GL version 3.3.10834 Compatibility Profile Context, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: [faithful32x32_1.8.zip]
	Current Language: English (US)
	Profiler Position: N/A (disabled)```
Interesting....
```java.lang.IllegalArgumentException: Name and ID cannot both be blank```

**Comment by Alexander01998** [comment]
@BoomBoomLHack So that's what happens when someone places the head?

**Comment by Eyremba** [comment]
@Alexander01998 Nothing. :/ I made my Wurst-version so that it does not crash if the head is placed. If I place it in singleplayer, nothing happens. If I try this ".give skull 1 3 {display:{Name:"CRASHES MINECRAFT, BE CAREFULL"},SkullOwner:{Id:"CRASH ID"}}" on a server, I get kicked with an "[Proxy] lost connection" message or something like this. (this is server-side, because Wurst no longer crashes because of this head). If I place it on a vanilla server, also nothing happens. If a player is destroying the skull in multiplayer, he is holding a normal skull in his hand, without NBT data.

**Comment by Al00X** [comment]
so , this is very bad :\ , not useful

**Comment by solidshadow96** [comment]
When is an update commin out i thought it was every friday @Alexander01998

**Comment by bob80333** [comment]
They come out on Fridays, but they don't come out every Friday.

**Comment by solidshadow96** [comment]
oh

**Comment by Nitrogen-Dioxide** [comment]
Ok, we need a way to don't get crashed on singleplayer first.

**Comment by Eyremba** [comment]
@Nitrogen-Dioxide like I wrote, I have done it so that it does not crash in singleplayer. But like I wrote above, also in multiplayer it is not working.

**Comment by Nitrogen-Dioxide** [comment]
@Eyremba 

Hmm so this way will not work, I'll take a look at more head tags to see if there is another way.

**Comment by Nitrogen-Dioxide** [comment]
Found another way :boom:

First I found this discussion explaining how the *value tag* works.

![2015-09-06_15-17-54](https://cloud.githubusercontent.com/assets/11248300/9705894/809aad88-54aa-11e5-8659-65136028ac75.png)

Then I found this auto generator which generates heads with custom urls, then I added the *https://www.wurst-client.tk/* link instead of an actual link of an png image: 

![2015-09-06_15-21-13](https://cloud.githubusercontent.com/assets/11248300/9705907/f6862dc4-54aa-11e5-8026-c7fb9503b566.png)

Well it is **more destructive** than the other way, because **the item skull can be generated at servers making you unable to join the creative server again without removing the buged item**. So it is the same thing that we said haha, protect wurst and makes everyone crashes.

It is caused because when Minecraft tries to use the image and since there is no image on the given link for the skull, it crashes . You can see my crash report here: [Crash Report](http://pastebin.com/w9z4Rx9m)


Note that **when someone loads/reloads a chunk with the head placed somewhere will have the same effect of nametags exploit**. If you don't crash **and give this item to someone that is not protected, he will crash too** .


Fu... My account is unable to join on a creative server now, I crash every-time I try to join :cry: .

[Crash Head Cmd](http://pastebin.com/zFHRbSkC)
[Discussion](https://www.reddit.com/r/MinecraftHeads/comments/24quwx/discussion_game_over/)
[Generator](http://www.dragnoz.net/custom-head-block-generator/)
[Crash Report](http://pastebin.com/w9z4Rx9m)

**Comment by Al00X** [comment]
Oh Nice :D ,

**Comment by Eyremba** [comment]
@Nitrogen-Dioxide some bad news for you: http://prntscr.com/8des83 Player1 placed the head with the NBT-Data you told us. He crashed. If he rejoins, he crashes again and again, like in your case. But Player2 is like you can see on this screen not affected by the crash, also If I reload the junks, rejoin, etc.

**Comment by Nitrogen-Dioxide** [comment]
Player1 had wurst and player 2 don't?

**Comment by Eyremba** [comment]
Player2 had only Vanilla MC 1.8

**Comment by Nitrogen-Dioxide** [comment]
So it is patched for 1.8. what?

**Comment by Nitrogen-Dioxide** [comment]
Well I'll test here with another versions.

( and see how often people got kicked )

**Comment by Eyremba** [comment]
@Nitrogen-Dioxide I used 1.8.0 which means it should already be patched.

**Comment by Nitrogen-Dioxide** [comment]
Omg thats very strange. I tested from 1.8 to 1.8.8 and any of them crashed. :disappointed: 

After that I tested other 1.8 hacked clients clients ( the top five of wizard hax ) **and all of them crashed**.

Are you saying to me that I just found a MCP client crasher??

**Comment by Eyremba** [comment]
Well, I tested it now with Player1=Wurst and Player2=Flare, and Player2 is not crashing, so Flare seems to be patched too or anything like this.

**Comment by Nitrogen-Dioxide** [comment]
@Eyremba 

Test with metro wolfram etc...

**Comment by solidshadow96** [comment]
REMOVED O_O
