### ISSUE TITLE
Auth servers are down when using Tor as proxy

### ISSUE THREAD

**Issue by kim-yannick** [Wurst-Imperium/Wurst-Client#2201]
Tor browser temporary creates a local SOCKS proxy to connect to the TOR Network. If I use this in Wurst, it fails to connect. If I don't use a proxy, it doesn't say that the servers are down.

**Comment by PgBiel** [comment]
Well... Wurst doesn't have support for proxy yet.

**Comment by kim-yannick** [comment]
It has, look at the changelog of 2.4.

**Comment by awakened-game** [comment]
WHY would you use TOR? No need to route through 6 countries to play minecraft, besides, public TOR exit nodes are all blocked, you need a private node, but you will lag a shit ton anyway.

Heres my setup:

unlisted bridge>unlisted entrance node> rand node>rand node>rand node>unlisted exit node

My system is tuned to prevent any DNS leaks too, so maximum anonymity.
Going through TOR, you should use an account that has never been on your real IP before, otherwise your IP history through minecraft will get you caught in onionland.

**Comment by kim-yannick** [comment]
I don't really need to get anonymous in MC. I just wanted to test the new
feature.
Am 12.09.2015 18:39 schrieb "awakened-game" <notifications@github.com>:

**Comment by Alexander01998** [comment]
Mojang's new auth servers block Tor and well known proxies. You will need something less suspicious.
