### ISSUE TITLE
wurst-client.tk error

### ISSUE THREAD

**Issue by avydrado** [Wurst-Imperium/Wurst-Client#2372]
https://wurst-client.tk/ ERR_CONNECTION_RESET Подключение к wurst-client.tk прервано.
Проверьте подключение к Интернету
Проверьте соединение кабелей, перезагрузите роутеры, модемы и другие используемые сетевые устройства.
Разрешите доступ к сети для Chrome в настройках брандмауэра и антивирусного ПО.
Если эта программа внесена в список программ, для которых разрешен доступ к сети, удалите ее из списка, а затем добавьте снова.
Если вы используете прокси-сервер...
Проверьте настройки прокси-сервера или попросите администратора задать верные параметры. В противном случае: Выберите Программы > Системные настройки > Сеть > Дополнительно > Прокси и снимите флажки напротив всех прокси-серверов.

**Comment by ThisTestUser** [comment]
ERR_CONNECTION_RESET Connection wurst-client.tk interrupted. 
Check the Internet connection 
Check the cables, restart the routers, modems and other network devices in use. 
Allow access to the network for Chrome in your firewall and anti-virus software . 
If this program is on the list of programs that are allowed to access the network, remove it from the list, and then add again. 
If you use a proxy server ... 
Check your proxy settings or ask your administrator to set the correct parameters. Otherwise: Select Applications> System Preferences> Network> Advanced> Proxies and uncheck all proxy servers.
Translation^^
And yeah its your internet so we can't do anything about it.

**Comment by avydrado** [comment]
why not working?
