### ISSUE TITLE
X-Ray destroying redstone

### ISSUE THREAD

**Issue by osa219** [Wurst-Imperium/Wurst-Client#250]
>Low quality issue fixed by an admin. Please write a better issue next time!

When I put a piece of redstone on the ground and activate X-Ray, it breaks.

When make an iron or snow golem and activate X-Ray, it dies.

**Comment by eioadea** [comment]
I confirm that Xray breaks redstone only in singleplayer, but this bug exists in xray mod (without Wurst)

**Comment by GlitchHead** [comment]
Cant dere me some kind of fix to this? i mean really its destroying blocks and certain types redstone redstone repeater and other redstone things this drives me crazy when i'm editing a redstone contraption and need to see whats going on inside and all the redstone just drops it self why does this even have pending confirmation its clearly destroying redstone.. (sorry just mad it nuked my red stone world)

**Comment by Alexander01998** [comment]
Hadn't seen this bug since MC 1.7 and needed to test if it's still there.

It does still exist, but now it only destroys redstone after a block update.

**Comment by solidshadow96** [comment]
In the last update the bug was fixed where using xray break's all redstone. this is now fixed but if the player interacts with any redstone with x-ray on it will then break the redstone please fix this.

E.G: if you have xray on and you click a button all the redstone within the players reach will be destroyed

see proof at https://youtu.be/L6mJ3kQ46pI

**Comment by Eyremba** [comment]
@solidshadow96 this also happens if you interact with freecam or with ghosthand with the redstone. It breaks then too.
