### ISSUE TITLE
Glitches Steve Texture

### ISSUE THREAD

**Issue by PgBiel** [Wurst-Imperium/Wurst-Client#33]
After using the Wurst client once, the steve skin texture gets glitched.
>**1 extra issue removed**. [Read the guidelines](https://github.com/Wurst-Imperium/Wurst-Client/blob/master/CONTRIBUTING.md) for more information

**Comment by Alexander01998** [comment]
> After using the Wurst client once, the steve skin texture gets glitched.

Please define "glitched".

**Comment by PgBiel** [comment]
The steve face doesnt appears, appears just a hair. Also the t-shirt of steve has a big "pink thingy" on its middle. It is an very odd texture.

**Comment by Alexander01998** [comment]
Any idea on how to reproduce this glitch?

**Comment by PgBiel** [comment]
I dont know.

**Comment by Alexander01998** [comment]
Well,
- this has never happened to me,
- I have never received messages from other people who have had this issue and
- there is technically no reason for Wurst to cause such an issue (it doesn't edit the Steve file),

so I assume that this issue was not caused by Wurst, but by something else - most likely a ResourcePack or a mod.

**Comment by PgBiel** [comment]
Thank you! I found out that it was my resource pack. Thanks anyway! ^-^
