### ISSUE TITLE
Realms outdated

### ISSUE THREAD

**Issue by Xzyer** [Wurst-Imperium/Wurst-Client#4]
When trying to join a Realms server you get a client outdated message.
I have tried an old fix of changing the realms version number in Wurst.json to the latest version (1.7.8 at the moment) but that fix appears to no longer work.

**Comment by Alexander01998** [comment]
Are you using Wurst for MC 1.7 or Wurst for MC 1.8?

**Comment by Xzyer** [comment]
I'm using the 1.8 client

**Comment by Alexander01998** [comment]
I just tested it and got the same error, but it definitely worked a couple months ago. Maybe Realms was updated to MC 1.8.1 or 1.8.2.

If we're lucky, it's just about changing the version number in the code so that Realms accepts it. Maybe I can even make an auto-detector for the current version or remove that version check entirely.

**Comment by Xzyer** [comment]
The right image is the 1.8.1 json file, and the left is yours, so the realms library appears to be outdated.
http://i.imgur.com/MNgJCWm.png

**Comment by Alexander01998** [comment]
It looks like I can't change any of the data that the Realms client sends. It is all being handled by the Realms library which I don't have the source code for.

And as you already figured out, using the newer version of the library doesn't fix it either, probably because it's incompatible with Minecraft 1.8.

So until Minecraft 1.9, this is a :bug: that I cannot fix.
