### ISSUE TITLE
DeathPos

### ISSUE THREAD

**Issue by scriptinator** [Wurst-Imperium/Wurst-Client#418]
A tool that shows you your last known coordinates before death

**Comment by pokeball99** [comment]
this should be merged into #408

**Comment by Alexander01998** [comment]
> this should be merged into #408

Things cannot be merged into Issues, that doesn't make sense.

**Comment by pokeball99** [comment]
what is mean is that this should be closed and then just have a comment saying that this is going to be added with it

**Comment by OMGchangeMYusername** [comment]
lol i just realised this when i was checking the closed issues,i agree it should be **moved** to issue #408 because they're actually identical and the DeathPos should be just an option at the Waypoints part which is located here :grinning:  
![waypoints](https://cloud.githubusercontent.com/assets/10786571/7168777/aa69c3fe-e3c8-11e4-8c57-0840a7aab9bb.jpg)
