### ISSUE TITLE
How can users see the data collected by analytics?

### ISSUE THREAD

**Issue by pokeball99** [Wurst-Imperium/Wurst-Client#420]

**Comment by Alexander01998** [comment]
The type of data that is collected can be found in the [Google Analytics privacy policy](https://www.google.com/policies/privacy/).

The results of the analytics cannot be seen by the users, although I might publish parts of them. An example of this would be a "users online" counter that shows how many people are using Wurst right now.

---
Just to remind you, all the data is collected anonymously, so no one, not even me, will ever know that you did something, that you have Wurst, or that you even exist. I will only know how many people did something.

It's nothing new either - you have all been tracked by Google Analytics for years. Every time you visit Google, YouTube, WiZARDHAX.com, Wurst-Client.tk, the exact same data is collected. It even happens when you use your smartphone - most apps have Google analytics built-in.
