### ISSUE TITLE
Suggestion: Bytecode Injection of Mods

### ISSUE THREAD

**Issue by Mimerme** [Wurst-Imperium/Wurst-Client#464]
It would be interesting to allow for users to create their own mods/hacks and drop them into a mods folder, similar to how Minecraft Forge does so. It would be beneficial to expand the fanbase of Wurst a bit farther, and for the community to develop new hacks. I would love to see this happen.

**Comment by pokeball99** [comment]
neat,but would most likely be a huge undertaking

**Comment by Alexander01998** [comment]
Adding custom mods, commands and other features is already possible through Forks & Pull Requests.

The advantages of this method over a Forge-like system are:
- Any fan-made feature can be pulled into the original version.
- All fan-made features must be open source.
- There's no risk of viruses (because they are open source).
