### ISSUE TITLE
Wurst v1.11

### ISSUE THREAD

**Issue by UnicornInExatacy** [Wurst-Imperium/Wurst-Client#475]
I'm not sure why but I cant delete Wurst v1.11 why am i trying to do such horrible thing so I can install Wurst v1.12 its seems to be something with Wurst-natives-23705842741256 witch is in        Wurst v1.11, by the way if you ask me heaved i tried to rename Wurst (latest v1.12) yes and the thing is I did and wean i close every thing and everything is good to go I lunch Minecraft and I go to edit profile and Wurst v1.12 is not listed there yes i went to the .JSON file and renamed it .... This is why I need to delete Wurst v1.11 because i need to rename my Wurst v.1.12 and I did but i wont let me use it so if i could just delete Wurst-natives-23705842741256 I would be able to delete Wurst v1.11  this way it would appear on my version list (minecraft luncher list)....

**Comment by UnicornInExatacy** [comment]
and yes i did delete METAINFO

**Comment by UnicornInExatacy** [comment]
never mind i had a coma in the names instead of a dot, but i can't delete Wurst-natives-23705842741256

**Comment by Nitrogen-Dioxide** [comment]
I'm not sure why but I cant delete Wurst v1.11 why am i trying to do such horrible thing so I can install Wurst v1.12 its seems to be something with Wurst-natives-23705842741256 witch is in        Wurst v1.11, by the way if you ask me heaved i tried to rename Wurst (latest v1.12) yes and the thing is I did and wean i close every thing and everything is good to go I lunch Minecraft and I go to edit profile and Wurst v1.12 is not listed there yes i went to the .JSON file and renamed it .... This is why I need to delete Wurst v1.11 because i need to rename my Wurst v.1.12 and I did but i wont let me use it so if i could just delete Wurst-natives-23705842741256 I would be able to delete Wurst v1.11  this way it would appear on my version list (minecraft luncher list)....

Just to make the read possible...
