### ISSUE TITLE
a downloaded ××× amount of times badge on the readme.md

### ISSUE THREAD

**Issue by pokeball99** [Wurst-Imperium/Wurst-Client#485]

**Comment by Alexander01998** [comment]
That badge does not exist. At least not yet.

**Comment by pokeball99** [comment]
Wouldn't u just make it and have it link up to the Google anilitics?

**Comment by Alexander01998** [comment]
Nope, that's not how they work. You need a server that generates the badge. And because the GitHub API only provides the number of downloads for an individual release, that server would have to check the downloads for each release and add them all together, which takes a lot more time and performance.

I tried making a counter in Google Apps Script, but GitHub doesn't accept it for some reason: http://googledrive.com/host/0B2YeSS9tm5zLfnZYeEhnMTNrR2k0aUt0RW91T2l6OGRZS0ZWYnJWUVRjb1ZPNktKX2JQNWs

See also: badges/shields#404

**Comment by pokeball99** [comment]
I would have it just run on your site and then prarse it into the readme

**Comment by Alexander01998** [comment]
> I would have it just run on your site and then prarse it into the readme

www.wurst-client.tk is running on Jekyll, so it cannot
1. fetch data from external URLs (with some [exceptions for GitHub repos](https://help.github.com/articles/repository-metadata-on-github-pages/), but not including the downloads) or
2. use cron jobs (e.g. refresh a download counter once per hour).

**Comment by Alexander01998** [comment]
Found out that GitHub does accept Google Apps Script images when using `drive.google.com/uc?id=FILE_ID` instead of `googledrive.com/host/FOLDER_ID/FILE_NAME`.

**Comment by Nitrogen-Dioxide** [comment]
96K of downloads?!

**Comment by Alexander01998** [comment]
> 96K of downloads?!

Much more if you count the downloads before Wurst was on GitHub.

Host|Downloads
:---|---:
MediaFire|65 476
Google Sites|165 713
GitHub|98 024
Total|329 213

![downloads-on-mediafire-2015-04-14](https://cloud.githubusercontent.com/assets/10100202/7134213/eb6f3b2e-e29a-11e4-926f-309b1cafafa3.png)
![downloads-on-google-sites-2015-04-14](https://cloud.githubusercontent.com/assets/10100202/7134212/eb6962da-e29a-11e4-8470-2b211726dbe5.png)
![downloads-on-github-2015-04-14](https://cloud.githubusercontent.com/assets/10100202/7134211/eb672db2-e29a-11e4-9fa2-da7fc26962b7.png)

**Comment by Alexander01998** [comment]
You know what? Let's make that badge count all the downloads.

**Comment by Nitrogen-Dioxide** [comment]
waaaa.
