### ISSUE TITLE
Killaura

### ISSUE THREAD

**Issue by Ericyeah** [Wurst-Imperium/Wurst-Client#516]
Issue: Killaura sucks.

Proposed solution: you should probably beg latematt or n3xuz to do something about it.

**Comment by Nitrogen-Dioxide** [comment]
Use killauralegit, it is better than any killaura you will ever see haha .

**Comment by Ericyeah** [comment]
@Nitrogen-Dioxide You obviously haven't seen n3xuzDk's killaura prioritization, it's brilliant.

**Comment by TekkitCommando** [comment]
Sarcasm... I don't like it...

**Comment by OMGchangeMYusername** [comment]
Ok i agree that i have found some better killauras and Wurst's killaura should be enhanced.
But the way you said it won't help either, you could've said it has to be enhanced not -it sucks-

**Comment by Alexander01998** [comment]
# Code of Conduct
- **Think before you react.** If you disagree strongly, consider giving it a few minutes before responding.

- **Ask questions, don't make demands.** ("What do you think about trying...?" rather than "Don’t do...!!!")

- **Don't insult.** Avoid using terms that could be seen as referring to personal traits. ("dumb", "stupid"). Assume everyone is attractive, intelligent, and well-meaning.

- **Be explicit.** Remember people don't always understand your intentions online.

- **Don't use hyperbole.** ("always", "never", "endlessly", "nothing")

- **Use emoji to clarify tone.** (":sparkles::sparkles: Looks good :+1: :sparkles::sparkles:" rather than "Looks good.")

**Comment by Nitrogen-Dioxide** [comment]
@Ericyeah Who is n3xuzDk? And... any pages that show his " killaura prioritization " ?
