### ISSUE TITLE
Autoaimbot For bowaimbot

### ISSUE THREAD

**Issue by trollmad3** [Wurst-Imperium/Wurst-Client#533]
So when the bowaimbot for Target locked comes up you have to click FAST to shoot him. On autoaimbot it will shoot him automatically. So you can get that kill easyer.

**Comment by OMGchangeMYusername** [comment]
wow i'm so lost can you please explain more?
"But for Autoaimbot it will aimbot for you so you dont need to click anything so it does it for you."
this part is unclear to be honest.

**Comment by trollmad3** [comment]
So when the bowaimbot for Target locked comes up you have to click FAST to shoot him. On autoaimbot it will shoot him automatically. So you can get that kill easyer

**Comment by Alexander01998** [comment]
> So when the bowaimbot for Target locked comes up you have to click FAST to shoot him. On autoaimbot it will shoot him automatically. So you can get that kill easyer

Releasing the right mouse button instantly once the target becomes locked is usually bad practice. When shooting at moving targets (especially players), you will usually need to wait another second or two so that you can shoot it in a moment where it is either

- not moving,
- moving more slowly or
- mostly moving by changing the distance to you (i.e. moving towards or away from you).

If you try to shoot it while it is moving left/right or quickly moving up/down, I can almost guarantee that you will miss it.

Therefore, a mod that shoots the arrow as soon as it can, regardless of the movements of the target, will make it much *harder* to hit the target.
