### ISSUE TITLE
.op command

### ISSUE THREAD

**Issue by Kadencrasher** [Wurst-Imperium/Wurst-Client#554]
Can you guys make a .op command?
Like here is the format:
.op <Admin_Name> <Your_Name> 
and it will make that admin make u op.

**Comment by pokeball99** [comment]
Already added

**Comment by Nitrogen-Dioxide** [comment]
It is called book hack.
But the way that you are saying how to do it is impossible.

**Comment by Nitrogen-Dioxide** [comment]
" BookHack allows you to insert links that execute commands into writable books. The nice thing about it: no one can see that it's a link, so you can trick admins into executing /op <your_name>, /pex user <your_name> add *, etc.

Here is how to use it:

Craft a writable book.
Type some text into it. Preferably a URL so that people will click on it.
Click Sign and give it a title.
Click Command Link and type in your command.
Now click Done.
Give it to the admin or to the person you want to troll. "

Note that this hack only works on **1.8** servers (not the ones that is 1.7 and accept 1.8) and some servers have a plugin to disable that.

**Comment by OMGchangeMYusername** [comment]
well i was going to ask about that @Nitrogen-Dioxide.
does bukkit or whatever disable it? please tell me how to know what plugins the server has.

**Comment by Nitrogen-Dioxide** [comment]
@OMGchangeMYusername No... and to know if the server have this plugin, just try to do it with a book :p (it costs times on survival, sometimes frustating :/ ).

**Comment by stiff4321** [comment]
How do you use the book command im having trouble getting oped
