### ISSUE TITLE
NBT-Editing Commands

### ISSUE THREAD

**Issue by Twixal** [Wurst-Imperium/Wurst-Client#594]
Well I know theres an /enchant command, but I would like to see more commands which you can use in Creative mode like 
changing Stacksize with /ss 64 
or item Damage /id 1355, 
maybe even a command to enhance potions 
and renaming with coloured names /name &4Sword.
Just some stuff to edit items... other than enchant :)
Thanks in Advance :)

**Comment by GummiBoat** [comment]
The renaming is already implemented (".rename", for colors use $ instead of &). It would be really cool tho to implement changing the Item-Damage or to customize Potions. (if that's even possible.. )

The Stacksize thing is kinda useless, because you can just open your inventory and middle-click stuff in creative mode to get a stack of it.

**Comment by Twixal** [comment]
Well there was a Client which was Leaked called Faurax (Ceanko Edition), the enchpot command worked and it even was possible to enchant with good or with bad effects all on level 99. It was also possible to add your own Potion Effects with Level and Duration :smile:

**Comment by Alexander01998** [comment]
Duplicate: #342

**Comment by MicroChip321** [comment]
is it possible to add a command what gives colour chat in minecraft servers for example .say $1hi

**Comment by GummiBoat** [comment]
@MicroChip321 No, because you have to send the "§" Symbol. (Minecraft uses that for color-codes.) And sending the § Symbol disconnects you from the server immediately without even sending the message.

**Comment by MicroChip321** [comment]
oh :( so can that be fixed with coding?
