### ISSUE TITLE
Meine Wust-Ideen :)

### ISSUE THREAD

**Issue by ravenje** [Wurst-Imperium/Wurst-Client#601]
Lieber Weinachtsmann...

Ich habe ein paar tolle ideen fuer deinen Wurst client :)
Hier ist eine liste :)

.rename:
	1. & Farb-Codes, also .rename &4Red &1Diamond Sword
	2. eine Item-Loren Funktion
	(.lore add &4Erste &8Lore | .lore remove 1 | .lore clear | .lore set 1 text) 
	3. 

.enchant:
	1. Einzelne Enchantments
	-	.enchant sharpness 10
	2. Enchantments Loeschen
	-	.enchant sharpness 0 | enchant clear | enchant clear sharpness oder so

.nbtedit:
	1. .nbtedit addattr MaxHealth 10
	2. .nbtedit name &4Baboschwert
	3. .nbtedit lore add | remove | clear | set
	4. .nbtedit enchant add sharpness 1 | enchant remove sharpness | encahnt clear sharpness | enchant clearall
	5. .nbtedit potion add regeneration 5 60
.cmdblock
	1. .cmdblock set say &4Server was Hacked
	2. .cmdblock clear
	3. .cmdblock rename &4Server (Um den namen des command-blocks zu Ändern)
	4. .cmdblock copy | .cmdblock paste

.head:
	.head <name>
        um den kopf des spielers der angegen ist zu bekommen (im gm1)

Beschreibung der Funktionen:
.cmdblock - CommandBlock Editor der Farben Supportet (Wen man auf dem server OP Hat)
.head - Spieler koepfe im Creative bekommen (z.b. .head Notch)
.nbtedit - Ein item nbt daten Editor (Creative)

Soo, nun zu anderen coolen sachen fuer wurst:

Disable Wurst:
	- Im wust menu ein [Disable Wurst] knopf um z.B.:
	- [Admin]: Mach jetzt ein Screenshot von deinem Minecraft und schicks mir!
	- [Ich]: Ok ^^ (Wust ausschalten xD)

.logchat add 7msg | .logchat alert 7tpa | .logchat (zuvorkommen) 7tpa /tpa <2>

.instantkick <username> | wen man op hat den Admin oder instant beim joinen kicken XD

.pt (.powertool):

.pt /summon PrimedTnt | auf das item in der hand diesen begehl Binden XD

Sign-Hack:
Man plaziert ein Schild
Schreibt drauf:
	Click mal
	auf das
	Schild ^^
dan auf Insert Command Clicken:
/command (/op name) (/pex user name add *)

Bookhack verbesserungs-idee:
	1. Eventuell ist es ja moeglich, in jede zeile 1 command reinzuschreiben, sodass man in die erste:
	/kickall
	und in die zweite
	/fly oder /gamemode 1 schreiben kann ^^

Buch:
	ein [§] Knopf fuer Farben :D

Chat:
	ein [§] Knopf fuer Farben bei .rename :D

.enderman (oder .btp oder sowas :D)
	Nutzt die .Blink funtion um sich dahin zu Blinken, wo man grade Hinguckt :D
	(wie bei /jump glaube in essentials :D)

	1. Variante:
		Ohne NoCheat: Ohne verzoegerung direkt tpn
	2. Variante:
		Mit NoCheat: Mit der noetigen zeit Teleportieren das man nicht Rumbuggt oder Garnicht tpt wird :D
		Solte man bei Settings Ambesten einstaellen koennen :D

.freecam:
	.freecam mode walk | Wie bei blink normal rumlaufen ohne zu fliegen :D
	.freecam mode normal | Das normale Freecam
	.freecam speed | Fluggeschwindigkeit bei normal :D 
	

.autocommand (.ac):
	.autocommand set /deop admin#/ban admin#.massban &4Server &5was &4&l&n&oHacked!

	
	Die idee ist, das sobalt man OP Bekommt der admin deopt und gebannt wird

.massban:
	.massban | Bannt alle spieler auf dem server (Logischer weise gets nur wen man OP oder ban rechte hat :D

.plugins:
	Testet die bekanteren Plugins aus, wie z.b. Essentials oder CraftBook, PermissionEx oder bPermissions :D
.commandfinder:
	Sucht nach bugs, wie /bukkit:me oder /bukkit:kill befehlen die gehen und zeig diese in einer liste an :)

.serverstatus:
====== Server Status ======
Cracked: No
Server: Spigot
Version(s): 1.7 - 1.8
Bookhack: Not Working
===========================

.status:
====== Your Status ======
Health: 19
Hunger: 20
OP: No
Armour: 100%
=========================

.autowarn
	Zeigt an, wen ein Gegner (Spieler) in die Reichweite des Spielers kommt

.fallcheck:
	Wen man auf einem Berg steht, und nicht weis ob man den sprung ueberlebt... 
	es soll anzeigen ob man Stirbt, oder ob man den fall ueberlebt, und mit wievielen Herzen

.umpickable:
	Macht es fuer pieler unmoeglich, das item das man grade in der hand hat aufzuheben :D

.stack:
	1. Im survival alles stackbare im inventar Stacken
	2. Im Creative bei .stack das item in der hand stacken | stack all alle items im inv stacken
	

.console <text>:
		So soll es funktionieren:
		Erst wird ein CommandBlock gesetzt, der ein Command ausfuert.
		Dan wird oben drauf ein RedstoneBlock oder Hebel gesetzt der den Block Aktiviert,
		Dan wird beides wieder entfertn

PS: Sorry Wegen der schlechten Rechtschreibung :D

**Comment by TekkitCommando** [comment]
Dear Weinachtsmann ...

I have some great ideas for your client :)
Here is a list :)

.rename:
1st & color codes, so .rename & 4RED & 1Diamond Sword
2. an item Loren function
(.lore Add & 4First & 8Lore | .lore remove 1 | .lore clear | .lore set 1 text)
. 3

.enchant:
1. Individual Enchantments
- .enchant Sharpness 10
2. Delete Enchantments
- .enchant Sharpness 0 | enchant clear | enchant clear sharpness or so

.nbtedit:
1. .nbtedit addattr MaxHealth 10
2. .nbtedit name & 4Baboschwert
3. .nbtedit lore add | remove | clear | set
4. .nbtedit enchant add sharpness 1 | enchant remove sharpness | encahnt clear sharpness | enchant clearall
5. .nbtedit potion add regeneration 5 60
.cmdblock
1. .cmdblock set & 4Server say what Hacked
2. .cmdblock clear
3. .cmdblock rename & 4Server (To the name of the command-blocks to change)
4. .cmdblock copy | paste .cmdblock

.head:
.head
to the head of the player is to get the angegen (in gm1)

Description of functions:
.cmdblock - Command Block Editor of colors Supportet (Who Has you on the server-OP)
.head - Player minds in Creative obtain (eg .head Notch)
.nbtedit - An item nbt data editor (Creative)

Soo, now to the other great things for sausage:

Disable sausage:
- In wust a menu [Disable sausage] button to e.g .:
- [Admin]: Mach now a screenshot of your Minecraft and schicks me!
- [I]: Ok ^^ (Wust off xD)

.logchat add 7msg | .logchat alert 7tpa | .logchat (preempt) 7tpa / tpa <2>

.instantkick | who to op has the Admin or instant when joinen kick XD

.pt (.powertool):

.pt / summon PrimedTnt | on the item in hand this begehl binding XD

Sign-hack:
They placed a sign
Writes it:
Click times
on the
Sign ^^
dan on InsertCommand clic:
/ Command (/ op name) (/ pex user name add *)

Facebook Hack improvement idea:
1. Maybe it's possible to reinzuschreiben in each line 1 command, so you first in the:
/ Kickall
and in the second
Can write / fly / or gamemode 1 ^^

Book:
a [§] button for colors: D

Chat:
a [§] button for at .rename colors: D

.enderman (or .btp or something: D)
Uses the .Blink funtion to get there blinking, where you hinguckt grade: D
(As in / jump believe in essentials: D)

1. Description:
    Without NoCheat: tpn directly without any delay
2. variant:
    With NoCheat: with the necessary time to the Teleport not Rumbuggt or Garnicht is tpt: D
    Settings can be Solte at einstaellen Ambesten: D
.freecam:
.freecam fashion walk | How to run around with flashing normally without flying: D
.freecam mode normal | Normal Freecam
.freecam speed | speed if normal: D

.autocommand (.ac):
.autocommand set / deop admin # / ban admin # .massban & 4Server & 5What & 4 & l & n oHacked!

The idea is that you sobalt deopped OP Gets the admin and will be banned
.massban:
.massban | Bans, all players on the server (logical gets only one who has the OP or ban right: D

.plugins:
Tests the bekanteren plugins, such as Essentials or Craft Book, PermissionEx or bPermissions: D
.commandfinder:
Searches for bugs, such as / bukkit: me or / bukkit: kill command the go and show them in a list :)

.serverstatus:
====== ====== Server Status
Cracked: No
Server: Spigot
Version (s): 1.7 - 1.8

Facebook Hack: Not Working

.status:
====== ====== Your Status
Health: 19
Hunger: 20
OP: No

Armour: 100%

.autowarn
Shows who is an enemy (players) in the range of the player

.fallcheck:
While standing on a mountain, and know not whether they survived the jump ...
it is intended to indicate whether one dies, or if you survived the fall, and with how many hearts

.umpickable:
Makes it up for Pieler impossible, the item that you just in the hand: D

.STACK:
1. In all stackable survival in inventory stacking
2. Creative at .STACK the item in hand stacking | all stack all items in the inv stacking

.console:
So it should work:
Only a Command Block is set, the ausfuert a Command.
Dan is on top of a RedstoneBlock or lever set the Enable the block,
Dan will both been removed in again

PS: Sorry Due to the bad spelling: D

He's German but i translated it xD

**Comment by TekkitCommando** [comment]
Forgive me if im wrong but i shouldn't be, when he says dan it means then

**Comment by OMGchangeMYusername** [comment]
that doesn't change the fact that this is **invalid**.

**Comment by TekkitCommando** [comment]
I know but i still translated his idea, lets not be rude

**Comment by OMGchangeMYusername** [comment]
what kind of rudeness is "that doesn't change the fact that this is **invalid**"??!!!

**Comment by TekkitCommando** [comment]
The way you said it i took it a little rudely sorry

**Comment by OMGchangeMYusername** [comment]
that means @Alexander01998 is the rudest one to you here.

**Comment by pokeball99** [comment]
How is this invalid?

**Comment by OMGchangeMYusername** [comment]
- **Don't put multiple Issues into one issue.** That makes them impossible organize and will likely get your issue ignored or removed.

**Comment by ravenje** [comment]
you ...
How do you like the idea?
: D

**Comment by TekkitCommando** [comment]
@ravenje The ideas may be good but please one idea per issue next time :), @OMGchangeMYusername  I dont think @Alexander01998 is rude at all, and @pokeball99 He is right about the invalid tag its part of the contribution rules

**Comment by ravenje** [comment]
I have so many ideas ...

**Comment by TekkitCommando** [comment]
I understand that :)

**Comment by ravenje** [comment]
the colors are really most important in .rename most importantly ...
.lore and .enchant sharpness 100 irgetnwie also ...
(and .nbtedit)

I am using Google translator to write this: D

**Comment by ravenje** [comment]
Wen wurst diese funktionenWho wurst these functions would have ... Were he the best client at the world has ever existed .. he is even now: D

**Comment by TekkitCommando** [comment]
Thanks for contributing to the client :)

**Comment by ravenje** [comment]
I hope that some functions I was proposed to be implemented
most .rename the colors and .enchant / .nbtedit

**Comment by Alexander01998** [comment]
The color thing is already implemented (`.help rename` for details).

**Comment by OMGchangeMYusername** [comment]
I didn't actually mean you do think he's rude,i just said that because alexander would've closed this and mark this as **invalid** anyway.

**Comment by Alexander01998** [comment]
The rest is just way too much for a single issue. The way this works is that each issue represents one suggestion or one bug report. This allows me to organize them and keep track of which suggestions are implemented, which bugs are fixed, etc.

However, if you put more than one suggestion or bug report into a single issue, this whole system no longer works. That means I can't keep track of which suggestions I accepted or rejected, which features are implemented and which bugs are fixed.

Please review the [guidelines for contributing](https://github.com/Wurst-Imperium/Wurst-Client/blob/master/CONTRIBUTING.md) to this repository. They contain everything you need to know about writing issues.
