### ISSUE TITLE
Spammer

### ISSUE THREAD

**Issue by OMGchangeMYusername** [Wurst-Imperium/Wurst-Client#607]
ok so recently i've been interested in the Spammer,but i don't have the slightest idea on how to actually use it,and how much i can make use of it.
i don't know how to make it repeat and stuff..
so there :bulb: i was like, what if Alexander made a page for Spammer on the wiki? 
like how to use it,what are its features.

**Comment by eveythingistaken** [comment]
Great idea

**Comment by Alexander01998** [comment]
Spammer has an integrated help.
All syntax's, tags, variables, etc. are explained there.

![](https://cloud.githubusercontent.com/assets/10100202/7318987/abafcb3a-ea91-11e4-98ed-9a7095155415.png)

**Comment by GummiBoat** [comment]
Well, the Spammer is really easy to understand. Each Line in the Window that Opens if you open the Spammer via ClickGUI represents one Text-Message in-game. So if you just want to spam multiple messages, just copy and paste the line over and over again. You can save that as a wspam-script (File -> Save spam to file) for later use. If you want to have a much more complex spamming, you can simply open (Help -> Introduction to WSPAM). You can define variables (for example <var google>www.google.com</var> defines the variable google, which you can use by typing "§google;". instead of that it sends the value www.google.com) You also can use Tags. (Help -> Available Tags) For example, if you want to spam 5 random numbers just use "<random number 5>" and it does that for you. Or if you want to send a message over and over again, and are too lazy to copy/paste it in every line, just use "<repeat NUMBEROFREPEATS>(next line)MESSAGE</repeat>"

I hope this should be enough, for those that don't understand the help-box.
