### ISSUE TITLE
Is it possible to keep OP or * permissions on a server?

### ISSUE THREAD

**Issue by ravenje** [Wurst-Imperium/Wurst-Client#644]
Is it possible to keep OP or * permissions on a server?
any way?
plese help

**Comment by GummiBoat** [comment]
Book Hack? (https://github.com/Wurst-Imperium/Wurst-Client/wiki/BookHack)

**Comment by ravenje** [comment]
i mean a way to keep it, if permission * is removen or i get deoped
maybe its possible to check permission's plugins (EssentialsGroupManager, bPermissions) to autogive permission *.* or **.**

**Comment by GlitchHead** [comment]
wow! GummiBoat nice idea i will try these!

**Comment by GummiBoat** [comment]
No Problem. The first Option is only for servers, that have Permissions-Ex. Since it's compatible with command-blocks, you should have no problem, doing that. The second Option is for basically every server that has commandblocks enabled. If you need more detailed informations about the Trigger-Command, feel free to ask.
