### ISSUE TITLE
Chat Book hack

### ISSUE THREAD

**Issue by failvenom** [Wurst-Imperium/Wurst-Client#670]
Make something similar to bookhack but in chat like : https://youtu.be/xAaYR3rLXDM?t=159
Pay attention to his cursor!

**Comment by Nitrogen-Dioxide** [comment]
Problaly this is possible only serverside :p I think you can't send codes in the chat :/

**Comment by GummiBoat** [comment]
The Chat-Line in the Video uses Advantage of the /tellraw Command, which also is compatible with the JSON Format and because of that with click_events. But you can't send Tellraw Messages as a normal User. I don't know if normal people's messages are in JSON too, but i don't think so, so i would say it's impossible to add it for users.

**Comment by Alexander01998** [comment]
Normal chat messages are sent as plain text.
