### ISSUE TITLE
Player Screen Mod

### ISSUE THREAD

**Issue by JackWurst** [Wurst-Imperium/Wurst-Client#683]
if this is possible, you'd be able to see other people's screen. Of course, there is already a mod for this, but it only puts your player in their perspective. With THIS mod, you'd be able to see everything in their minecraft window. ie: when they're in their GUI, when they're typing in chat, what items they are holding, etc.

**Comment by GummiBoat** [comment]
That's not possible, the packets don't give that much information to the server. For Example the Chat: The Chat is completely on your client. And if you type a command and press Enter, a packet gets sended through your client to the server (that's why we are able to have .commands) and the server sends it to the other players. (atleast that's how I understood it.)

But you can see, what they are holding/wearing if you type ".invsee PLAYERNAME" and you can watch their movementtts if they are close enough ".rv PLAYERNAME".
