### ISSUE TITLE
DeathTouch

### ISSUE THREAD

**Issue by CrazyHacker007** [Wurst-Imperium/Wurst-Client#687]
Anibody who you touch insta die!!!
Great for PvP.

**Comment by GummiBoat** [comment]
Wear Armor with Thorns on it. If it's high enough, the enemy will die instantly. (".enchant" if you have gamemode)

**Comment by OMGchangeMYusername** [comment]
Well.. insta die isn't possible even with Thorns III on. (max thorns is III unless you have gamemode or somethin')
also,regardless of whether that can work or not,Wurst has nothing to do with it.
unless you actually meant something supernatural like he dies instantly because you have Wurst,that's impossible.
