### ISSUE TITLE
The hacked clients' future?

### ISSUE THREAD

**Issue by OMGchangeMYusername** [Wurst-Imperium/Wurst-Client#719]
ok i think this is very important and you guys have to check it out,[CheatBreaker] (http://www.reddit.com/r/hcteams/comments/34p3wr/heres_everything_you_need_to_know_about/) <<this thing right there made me confused all the day! so i thought of having your opinions. @Alexander1998,@Nitrogen-Dioxide,@GummiBoat,@GlitchHead..
I tried to mention most of the coding related peeps <3,so please respond.

**Comment by GummiBoat** [comment]
Okay. I read through the article and there are a few issues with that. First: It's a Forge-Client Modification. So Servers will be forced to allow Forge-Modifications. (There are currently four servers, that provide a) the Support to Forge-Modifications and b) the Plugin from CheatBreaker (or something similar, that can tell if CheatBreaker is used or not.) You can get the list here. http://www.cheatbreaker.com/protected-servers/ )

I guess it won't affect very much servers. As we all know, Humans are lazy. Most Servers wil just stay with the common Anti-Cheat Plugins, because they think that they're enough for the most major Cheats. And secondly, Users don't like to be forced to install Modifications to play. (And many Users have Problems with installing Mods. We all know that.)

For the Modification itself.. well.. it seems true, that it's providing that "safety". But I also think, that there will be ways around it, as always. It's with any other Anti-Anything Program too. First the Problem shows up, and then the solution is found. You know, Cat and Mouse.

So, my final Opinion is: There will be some servers, that will change to that. But I don't think that every Server will have this. So we have to wait, how things develop.

**Comment by GlitchHead** [comment]
"CheatBreaker, as a client-side application" well 30% of people will download this to play on the server...

"First and foremost, we do intend to allow other servers to adopt CheatBreaker. That means if you get banned on a CheatBreaker protected server, you're banned from EVERY protected server." This does not sound good for the hackers and normal players most likely whatever the plugin sends to mass ban a player on ALL protected servers most  likely can be duplicated to ban any player from ALL servers for no reason most likely.

**Comment by Alexander01998** [comment]
Even if CheatBreaker would gain enough popularity to be used on a popular server, hacking into it should be super easy.

- The things that CheatBreaker does on the client side, like scanning for and deleting hack clients, don't have to be done. They can either be removed from the original CheatBreaker or not be done by a fake CheatBreaker.

- The data it sends to the server can then be sent by Wurst as if nothing happened. The result of CheatBreaker's scans for ~~nude pictures~~ hack clients can be replaced with whatever it would send if it had not found anything.

> "First and foremost, we do intend to allow other servers to adopt CheatBreaker. That means if you get banned on a CheatBreaker protected server, you're banned from EVERY protected server." This does not sound good for the hackers and normal players most likely whatever the plugin sends to mass ban a player on ALL protected servers most likely can be duplicated to ban any player from ALL servers for no reason most likely.

We have had that before, it was called MCBans. Any server owner could give any player nearly any reputation, so people could globally ban anyone who joined their server. It is probably safe to say that MCBans failed, as I have only seen a single MCBans server in my life (and got globally banned by a 12 year old :wink:).
Another one of these systems is called Glizer and it is still active today, but it is limited to a small number of German servers.

**Comment by OMGchangeMYusername** [comment]
> If you're caught cheating, you will be marked for a future ban, similar to systems like VAC and ESEA, among others. When the banwave is issued, you will be PERMANENTLY banned from all CheatBreaker-protected servers.
This ban is an IP Ban, HWID Ban, and Minecraft UUID ban.

i mean,that's scary..
but thanks guys! i really appreciate all of your replies :smiley:

**Comment by Mimerme** [comment]
Such Anti-Cheating mechanisms like these are often found in extremely competitive games such as Counter-Strike (Most popular is the ESEA Client). But note two things, 1) Counter-Strike is a competitive game with several professional e-sports leagues, Minecraft eh.....not so much. 2) Remember how long it took for Forge to update? Or even just MCP? If it takes that long again RIP Cheat-Breaker.

I know that servers like Overcast have competitive leagues  and their competitive servers could implement these systems because their players aren't just your normal casual every day player.

**Comment by Nitrogen-Dioxide** [comment]
Anti cheat client side is not something new...
Client side protection is used by an brazilian server called "craftlandia" ( I'm brazilian, and I play there sometimes, it have a "cracked mineplex" ) well... they just made their own client... It sends a information to the server. The flaw on that, is what @Alexander01998 said. You can send a fake "I'm using your anticheat" message. 

But  there is a better flaw ;) it uses liteloader, just like the forge anti-cheat, so I have x-ray installed xD .

**Comment by OMGchangeMYusername** [comment]
@Nitrogen-Dioxide yes i did.
Well.. at the very least,you have some experience. But when it comes to codes or any complicated stuff,i'm pretty sure i'm the worst here :stuck_out_tongue:

**Comment by mcccs** [comment]
And WEnigma can deobfuscate cheat breaker's code. And it will!
