### ISSUE TITLE
automatic alt login

### ISSUE THREAD

**Issue by llaurenss** [Wurst-Imperium/Wurst-Client#766]
when i import a list of 30 alts using the import alt button. it should be nice that it automatically removes the alts that doesn't work. because only 10 of the alts are mostly working.

**Comment by Alexander01998** [comment]
Finding the broken alts in a list can only be done by attempting to login with all of them.
The problem is that logging in with too many broken alts at once causes Mojang's authentication servers to ban your IP address, so you won't be able to login with any account for 24 hours.

I recommend checking your alt list with an alt checker before importing it to Wurst. Alt checkers prevent your IP address from getting banned by using proxies to check the alts.
