### ISSUE TITLE
Scrambler Solver!

### ISSUE THREAD

**Issue by Loltage23** [Wurst-Imperium/Wurst-Client#769]
Ok So on some servers they have the scrambler plugin ![](http://i.imgur.com/SmI68F8.png) It's an instant type thing

**Comment by failvenom** [comment]
So what do you want Alex doing with it?

**Comment by GummiBoat** [comment]
I guess he wants something that listens the chat for that specific message, gets the Word and sends it instantly.

I don't think you'll get this through, especially since plugin-specific additions won't get implemented before Wurst is basically finished. 

But you could achieve that by using the "Macro KeyBind Mod" for liteloader. I won't tell you how you can achieve it, but it's definitely possible to do that in there.

**Comment by Alexander01998** [comment]
Need some sample servers.

**Comment by Lakitu** [comment]
A list of servers using ChatReaction:
http://minecraft-mp.com/plugin/chatreaction/

Sometimes you have to hover, calculate what 3*3 is, or you have to say what the colour of grass is. That makes it very hard to add.

**Comment by JPaulMora** [comment]
you can make it to search the text *"to type the word"* and return the text after it
