### ISSUE TITLE
Platform / MagicCarpet

### ISSUE THREAD

**Issue by mcccs** [Wurst-Imperium/Wurst-Client#781]
Same of the /platform in the singleplayercommand mod.
Places a block under you

**Comment by SpyroDash** [comment]
I might be stupid but could something like this be combined with the fly hack to like place a block under you so you could get around the getting kicked for flying thing

**Comment by pokeball99** [comment]
I think he is referring to something like magic carpet hack like in other clients

**Comment by mcccs** [comment]
This helps to build in air

**Comment by bazzz1512** [comment]
It would really help. I also suggested it for improvement of the bunker mod, but it was told to me that you can't place blocks in mid-air.

**Comment by GoGoJJTech** [comment]
There's a mod that I use all the time called "Schematica"

It lets you import and export schematics, and rebuild them in servers etc. However, placing blocks in mid-air doesn't work, so I'm gonna assume you'll need heavy trickery to get it working.

However, you can place blocks in mid-air if they're adjacent to ghost blocks. But that's a whole other story.

**Comment by bob80333** [comment]
Would placing on air blocks work?  It probably wouldn't be able to bypass NoCheat+, but there would at least be the mod for vanilla servers.

**Comment by Eyremba** [comment]
There is a client which has SafeWalk with "ScaffoldWalk" as an Option under SafeWalk.
Please watch this short video about this: https://www.youtube.com/watch?v=x1qFmylrers

This video was made on the NCP testserver with the latest NCP version. As you can see, it works perfectly with NCP.

And for @Alexander01998, here is the source: http://hastebin.com/kegolufala.avrasm

**Comment by OMGchangeMYusername** [comment]
Jep that's Tyrant, Tyrant is so good.

**Comment by Eyremba** [comment]
@OMGchangeMYusername Yes it is Tyrant. :D The only things missing in Tyrant is HealthTags, better step because it is buggy, and a new damage bypass because NCP fixed it. By the way: SAME for Wurst: Both damage bypasses of Wurst (".damage" and "Fly" if "YesCheat+" is active) has been fixed and are NOT working on the newest NCP version. (Test in on the NCP testserver, they have the newest NCP version and falldamage is enabled.) Maybe I make a new issue for that.
