### ISSUE TITLE
Killaura through walls

### ISSUE THREAD

**Issue by eveythingistaken** [Wurst-Imperium/Wurst-Client#784]
Hey Alex, If you've seen the new KiLO Client, you may have seen that there's an option for killaura so that you can hit through walls. If you could add that, it'd be sick.

**Comment by OMGchangeMYusername** [comment]
i don't think it'd work for any wall but i guess i've saw it before.
btw important advice,**I've heard some rumors that KiLO client can be so harmful,someone went as far as saying it can turn off your PC to the point where you can never turn it on again!!**
idk if that's right or not,but i decided to not take the risk.

**Comment by Nitrogen-Dioxide** [comment]
@OMGchangeMYusername You can turn it on again if windows/ios has exploded xD.

**Comment by OMGchangeMYusername** [comment]
@Nitrogen-Dioxide i'm not actually saying it **will** do that but someone said it's possible for it to do so!
it might also dump your username and password into the maker's alt list xD
also,i don't use clients before i make sure they're secure :P
anyway,that's not 100% sure,but as i said i won't risk using it.

**Comment by GlitchHead** [comment]
#malware

**Comment by pokeball99** [comment]
well,it is on wizard haxs,so if it was a jrat,then they will get some major shit for promoting it

**Comment by Alexander01998** [comment]
KiLO is safe, I checked.

**Comment by OMGchangeMYusername** [comment]
this is a topic on [Wolfram Forums] (http://shadowspl0it.com/forums/showthread.php?tid=59). read the reply.
It says it uses virus like features but i think he mentioned a weird way of using it,anyway if you're sure it's 100% safe,then my bad..

**Comment by GummiBoat** [comment]
@OMGchangeMYusername You didn't read quite through the reply, did you? He said, that it's POSSIBLE for the Client, to gain permissions for the system, due to an exploit in Java. And at WORSE it can destroy your computer.

But he also said, that it's possible to deny those permissions by using some different methods, so that you have the client and are safe. So since Alexander said it's safe and if you are using the mentioned methods, you should be fine by using KiLO.

For the "stealing Passwords" thing, he wrote that there are "rumors" that the coder of KiLO had written another hacked client, called "Matix", which stole your account data.

BTT: I really think that hitting through walls is incredibly useful. But is it bypassing NoCheat+ or not?

**Comment by OMGchangeMYusername** [comment]
@gummiboat You didn't read quite through my reply, did you? I said,that it's POSSIBLE for the Client, to ~~FUCK~~ your system, and it can even destroy your computer.
But i also said, that he mentioned a weird way of using it (idk why i didn't say "using it safely")
For the "stealing Passwords" thing,he **confirmed** that the staff is the same as Matrix later.

BTT: i have seen the hitting through walls,it's so cool :D
