### ISSUE TITLE
OP-Sign and Crash Item!

### ISSUE THREAD

**Issue by TigrexHD** [Wurst-Imperium/Wurst-Client#801]
https://www.youtube.com/watch?v=_bmlyu_TtyA

OP-Sign: 7:00 - 8:13
Crash Item: 14:29 - 15:00

**Comment by Alexander01998** [comment]
I am aware of GarPloit, Helios, etc. I'm just waiting for someone to share it.

**Comment by pokeball99** [comment]
what do GarPloit and Helios do?

**Comment by failvenom** [comment]
Op sigin is basicly duplicate of #622

**Comment by ICouldntUseMyRealNameSoIHaveThis** [comment]
@pokeball99 Those are hacked clients with force OP signs. (At least Helios has it).
@failvenom 1. It's not the same, the other one is general commands (by "*general commands*" I mean any command) that can be run. This is just about ForceOP on a sign.
2. I think Alex would have marked "duplicate" as a tag by now...
3. This also has crash item, which doesn't make it an exact duplicate.

**Comment by failvenom** [comment]
@ICouldntUseMyRealNameSoIHaveThis  Command sign just runs the the command /op YOURNAME
And thats exactly what #622 does :P

**Comment by failvenom** [comment]
@Alexander01998 I belive i have found a crack for Helios

**Comment by GummiBoat** [comment]
Well. Test it. Proof it. Share it.

**Comment by failvenom** [comment]
Ive tested it but i could not find any servers that are compatible with op sign and crash item 
https://mega.nz/#!tMQTSYqA!fgmA5gmGVD_0C0_hkMn0MMwgaUejVeEcARQlkBPmOy0

**Comment by bob80333** [comment]
OP sign may have been patched in update: http://www.pcgamesn.com/minecraft/minecraft-patch-185-cracks-down-on-reported-security-problems

**Comment by Spassvogelw** [comment]
Does anybody know a cracked Weepcraft Version?

**Comment by GummiBoat** [comment]
@bob80333 Yup, GamePedia stated the same. [Link](http://minecraft.gamepedia.com/1.8.5) And many different other sites too. BTW, the Issue with the exploit is currently not visible for normal users. So it seems to be the real one.

@Spassvogelw No. This is not even the right place to ask that.

**Comment by GummiBoat** [comment]
Update:

 The Crack seems to be real.

I can't access the exact name of the CrashItem right now, but the Sign is really simple.
(I just can state again, that there are too much characters and illegal ones too.)

The Sign is using a vanilla(!) exploit and is due to some mistakes from mojang in a higher command-priority as everyone else (even higher as command blocks.) so you simply can just op yourself with them. yay!

I currently only can give you an example of /setblock and the theory of the /give, because apparently there are some issues with the /give for me..  I don't know exactly what's going wrong, but...  maybe I'm just doing something horribly wrong. Anyways!

Setblock:
```
/setblock ~ ~1 ~ minecraft:standing_sign 0 replace {Text1:"{text:\"\",clickEvent:{action:run_command,value:\"/op USERNAME\"}}"}
```
So in theory, the /give should look like this:
```
/give @p minecraft:sign 1 0 {BlockEntityTag:{CustomName:"#",Text1:"{text:\"\",clickEvent:{action:run_command,value:\"/op USERNAME}"}}"}}
```
But surprisingly it's not working. I also tried to remove the "" from Text1, but that didn't do it either. So, if anyone knows what's going wrong, he can correct me if he wants to.

**Comment by failvenom** [comment]
@GummiBoat Take a look at this

![](http://puu.sh/i00Ft/affd04c36e.png)

**Comment by GummiBoat** [comment]
@failvenom yes, that probably means that it's not possible, because it's a vanilla bug. Bukkit already patched it and now Minecraft did too. But you know, server owners are mostly lazy with updating their servers. (I honestly don't even know one vanilla server, but you'll find one for sure.)

Anyway, I still can't access the Issue. So I can't tell you if it was patched or not. But it still is possible to do Sign- and BookHacks. (Not as "powerful" as they were, but still possible.)

**Comment by Alexander01998** [comment]
> (I honestly don't even know one vanilla server, but you'll find one for sure.)

ServerFinder: ~50 servers per minute

**Comment by failvenom** [comment]
@Alexander01998 
How to use server finder.
1. Find your ip
2. Put it in the server finder box.
3.Start.

**Comment by wizardhax** [comment]
Is there a cracked version of Heliosworking on the date of 31/05/2015?

**Comment by WurstContributer** [comment]
Nope.

**Comment by wizardhax** [comment]
Is there a working op-sign for a version less than 1.8.4?

**Comment by bobob22** [comment]
couldnt you just inject a dll with gamemode=1
i have no idea how to code so

**Comment by GummiBoat** [comment]
@bobob22 That's not possible.

**Comment by bobob22** [comment]
aw man i wish hacking was easy

**Comment by bobob22** [comment]
wait a minute could a hack effect a command like
/give NAME {text:"",clickEvent:{action:run_command,value:"/op USERNAME}"}}
i am in a server trying it just trying to clear peoples inventory [im op]
but does this run the command from console so when a admin checks logs it says CONSOLE: has healed all players?
cause if so ima use this in plotme server get added

**Comment by GummiBoat** [comment]
Okay, I don't quite get what you want, but. The /give Command is not even possible. I don't think that you understand NBT correctly. The ClickEvent is only available for Instances that use JSON to display Text, so it's for Books, Signs and the Tellraw Command. You CAN give yourself Items with NBT Data, but look a few posts above, that's how you do it.

But you can't run a command from a client as the server, unless you are able to hack the server itself.

You only can run commands as "console" via Command-Block. If you have one, run every command with that.

**Comment by bobob22** [comment]
oh ok thanks for letting me know i was wondering why it didnt work then i thought ^^

**Comment by bobob22** [comment]
ok well ima test some other ideas i have an i dont have NBT im useing via minecraft /i an itemdata

**Comment by WurstContributer** [comment]
@GummiBoat Anvil? To find name of crash item?

**Comment by GummiBoat** [comment]
Ah, I don't think that works, because the Anvil can't display the characters correctly either, as far as I know, but it's irrelevant, because the "new" Crash Item is way more funny and even works on every Bukkit Server.
