### ISSUE TITLE
Better inventory see .invsee

### ISSUE THREAD

**Issue by trollmad3** [Wurst-Imperium/Wurst-Client#802]
On the wurst command .invsee i want to see a persons inventory and it only shows ONE item if i try to move that item a different item will show i would really like a new .invsee

**Comment by OMGchangeMYusername** [comment]
That is intended,can you please stop duplicating and opening a lot of useless issues?
see #262 if you're not convinced.

**Comment by GummiBoat** [comment]
That's sadly not possible, because the server won't give you more information than you already get with .invsee.

And @OMGchangeMYusername .. calm down. <3

**Comment by trollmad3** [comment]
@OMGchangeMYusername Is always yelling at me beacuse its a dupe. LIKE JEEZ calm the hell down already.....

**Comment by OMGchangeMYusername** [comment]
@GummiBoat thanks. :+1: 
@trollmad3 is always opening issues and doesn't even search if it was already suggested/mentioned.
i'll recommend you using this syntax: 
if you want issues regarding invsee you should use the search and type "is:issue invsee in"
remember to remove the "is:open" because it's most likely closed,use any often used words for any other suggestion,for example if you want to talk about Mineplex's update (Killaura targets dead players) you can maybe use "is:issue mineplex in" or so...
i hope you use it next time,some more advanced search syntax [here] (https://help.github.com/articles/searching-issues/).
i hope i helped,i took a little time on this comment..
