### ISSUE TITLE
How to stop .goto?

### ISSUE THREAD

**Issue by OMGchangeMYusername** [Wurst-Imperium/Wurst-Client#834]
woops..
oh i was just using .goto but i don't seem to be able to stop it,it might be because of the y coordinates?

**Comment by Alexander01998** [comment]
`.t goto off`

**Comment by OMGchangeMYusername** [comment]
@Alexander01998 Thanks,sorry i was using `.goto` without the .t...
anyway does it stop immediately if it reaches the position?i set the y coordinates for a little higher place in a superflat world,it froze me at the x&z coordinates!
i was even in creative but it didn't seem to be able to use flight or the ordinary creative fly?

**Comment by Alexander01998** [comment]
> does it stop immediately if it reaches the position?

Yes.

> it didn't seem to be able to use flight or the ordinary creative fly?

If you have Flight (vanilla Flight or Wurst Flight) enabled **before** you type the `.goto` command, it will calculate the shortest flight path and fly there.
If not, it will calculate the shortest walking path and walk there.

> i set the y coordinates for a little higher place

Attempting to walk to a position in mid-air without having Flight enabled will give you an error before even starting to walk, because it will not be able to find a path.
When walking or flying through difficult terrain (half slabs on the ground, weird curves, etc.), it can sometimes get stuck. In that case, you will have to manually stop it using `.t goto off`.

**Comment by Mathiaspro** [comment]
Its a bug that when i turn on LSD non of the colors are comming up
