### ISSUE TITLE
Fly bypass nocheatplus

### ISSUE THREAD

**Issue by ravenje** [Wurst-Imperium/Wurst-Client#851]
Garploit has a fly bypass function
https://www.youtube.com/watch?v=AJHuBiYaE64
its work on NoCheatPlus server's (GommeHD, Hive, etc...)
can you add this in wurst 2.0?

**Comment by GummiBoat** [comment]
Should be possible. But the Client is using Exploits only for his functions. So it's very likely to be patched in future versions.

"Fly" Exploit:
   Damages you at the start so that NCP thinks, that you're actually falling. That's also why he flys so     slow on Gomme. And he can't control up/down.

CommandBlock "Exploit":
  Well, we discussed this already in the NBT-Command Issue. As soon as Wurst 2.0 is released, you'll be able to do the same.

Potion "Exploit":
  Same as CommandBlock. Just a Potion with crazy NBT Data on it. Nothing special.

Chest Exploit:
  This one is interesting, but it already is kinda public. It's just giving you a chest, that contains a HUGE Amount of (probably) empty NBT-Data Array LIsts. Minecraft fixed the Single Use only, but you can put multiple Chests into a Chest, so if there are too many, the packets get too big and it crashes your client. You could also just throw a bunch of chests into your victims inventory.

And the two Vanilla Exploits.. meh.~

**Comment by GummiBoat** [comment]
You can try the Fly Exploit by yourself tho. Go on a NoCheat Server, activate Glide, jump on Top of a Cactus and jump off immediately. you should be able to glide around freely.

**Comment by Alexander01998** [comment]
Pretty easy to do:
- `.damage`
- Glide on
- Profit!

Can probably also be done with a WSPAM script, but I'll add it as a mod anyway.

**Comment by GummiBoat** [comment]
On all Servers I tested (that had NCP+) the ".damage" command didn't work o_ô With or without YesCheat+ enabled... Or am I just doing something horribly wrong?

**Comment by Alexander01998** [comment]
> On all Servers I tested (that had NCP+) the ".damage" command didn't work o_ô With or without YesCheat+ enabled... Or am I just doing something horribly wrong?

They need to have both NoCheat+ and fall damage. Most NoCheat+ servers have fall damage disabled.
See #540.

**Comment by GummiBoat** [comment]
> Most NoCheat+ servers have fall damage disabled.

Meh. That sucks. I'll stay with the cactus method. Lel. (Should be possible with any method that damages you, right?)

**Comment by Alexander01998** [comment]
> Should be possible with any method that damages you, right?

Yes.

**Comment by Nitrogen-Dioxide** [comment]
Thats an old thing... The resilience version that I have here. Have this exploit.

**Comment by ravenje** [comment]
1. It not working on Bedwars on Gomme ( and many  other servers )
1. I glide too fast down if it work :/
