### ISSUE TITLE
Import Alts not clickable?

### ISSUE THREAD

**Issue by ilyaV1234** [Wurst-Imperium/Wurst-Client#866]
Whenever I hit Import Alts it doesn't do anything, it works sometimes but usually doesn't work. No Error Code appears. 

> OS X Yosemite Java Version 8 Update 45

**Comment by GummiBoat** [comment]
I clicked on that Button 250 Times, and it worked everytime. Stop using apple. Come to the **bright** side of life, use windows.. (get it? because *windows* let light into your room.. and bright side...? k, i'll kill myself.)

Oh, btw, keep your launcher open (Profile Settings -> Launcher Visibility) and look if an error appears there.

**Comment by Alexander01998** [comment]
Look behind the Minecraft window.
The Import Alts window will always be on top of the Minecraft window for Windows users, but that is not possible on Mac.
