### ISSUE TITLE
Color codes in Commandblocks

### ISSUE THREAD

**Issue by ravenje** [Wurst-Imperium/Wurst-Client#895]
It is possible to write colors to command blocks on multiplayer server's with op
can you add a $ color support for them?

**Comment by GummiBoat** [comment]
How exactly do you mean that? If you want to send colorized Chat messages, use the /tellraw command...

**Comment by ravenje** [comment]
No.

**Comment by ravenje** [comment]
I mean it so:
/give @p minecraft:iron_sword 1 0 {display:{Name:§4Name,Lore:[§3Lore]}}
becaus a .lore command will not added :(

**Comment by GummiBoat** [comment]
This will be covered by #342. And btw, you can't replace stuff, that a command block sends, because the block sends it directly to the server, and not through the client first.

**Comment by ravenje** [comment]
No, thats not real.
I did it in 1.7.2 with a mod
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1288788-all-u-want-create-and-edit-items-entities-spawners

In the mod:
I placed a command block and at the same time a pressed r on the ground, then i clicked command block and write a colored command, then i right-clicekd the command block and pressed ok

now the comamndblock is colored on a server =P

it works, but the mod is not updated to 1.8 at this time :(

**Comment by GummiBoat** [comment]
The Mod you sent just changes the name, exactly the same way Wurst does it. But instead of §, Wurst uses $, because you can't use § in the normal Chat bar.

Or if I missunderstood you, and you mean that the displayed Command in the Box is colorized.. well.. it's possible if you modify the Block with an NBT-Editor, I guess. But for what reason could that be useful? ô.o

**Comment by ravenje** [comment]
believe me, it is possible
