### ISSUE TITLE
Wurst Mcpatcher support

### ISSUE THREAD

**Issue by mcccs** [Wurst-Imperium/Wurst-Client#916]
MCpatcher is an alternative of optifine

**Comment by GummiBoat** [comment]
Optifine is giving you the ability to change every little detail directly and ingame to increase performance or the quality of your graphics.

MCPatcher is just increasing the quality of your graphics and allows Texturepacks to access specific detail-changes. Therefore it is not a direct alternative of Optifine, even i it's also doing its own part in reducing lag for your minecraft, while coming with a lot of features.
But it definitely is better than optifine.

But I honestly think most people want to have Optifine because of the zooming function and connected textures and don't really need the "increase of performance" (Optifine is doing horribly in that point.) that is supposed to be granted.

**Comment by Alexander01998** [comment]
MCpatcher is a tool for installing HD TexturePacks (now known as ResourcePacks) that was used in the Beta versions of Minecraft.
MCpatcher is obsolete, as its features are now part of vanilla Minecraft.
