### ISSUE TITLE
Wallhack & Instant item stealer

### ISSUE THREAD

**Issue by Inspector784** [Wurst-Imperium/Wurst-Client#923]
Wallhack is preety self explenatory. Actually see the player skin item and other stuff thorugh the wall.

ALSO make item stealer take everything from nearby chests instantly and automatically if chosen!
So option:
Wallhack Player/Mob/Both
Wallhack Distance - The distance to render Enteties / Mobs / Players

Item Stealer = Activate item stealer
Item Stealer Instant - Instantly steals everything from the chests on right click (Wont even open gui just right click on the chest and onto the next one)
Item stealer auto - Automatically steals from nearby chests

**Comment by GummiBoat** [comment]
Item Stealer is already implemented, (ChestStealer), you need to rightclick the Chest you want to steal from tho.

WallHack seems kind of unnessecary tho, because there already are ESP's for that. (MobESP / PlayerESP) and rendering the entire skin seems pretty resource heavy. Also you can increase the size of nametags (NameTags), so you always can read them as long as the player is in your range.

**Comment by Nitrogen-Dioxide** [comment]
@Inspector784 Don't make multiple "ideas" in the same thread, make them separated.
